INSERT INTO augments (augment_id, aname, descrip) 
	 VALUES 	('693', 'Pirates', 'Mercenary units have a @Chance@% chance to drop @Gold@ gold when they kill an enemy. Gain a Quinn.'),
	('706', 'Scholar Crest', 'Gain a Scholar Emblem and a Zyra.'),
	('776', 'Break Even II', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('858', 'Four Score', 'Gain @NumChamps@ random 4-cost champions.'),
	('777', 'Break Even III', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('877', 'TFT6_Augment_BrawlerHPVeteran_Name', 'TFT6_Augment_BrawlerHPVeteran_Description'),
	('726', 'Syndicate Crown', 'Gain 2 Syndicate Emblems.'),
	('775', 'Break Even I', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('823', 'Hextech Unity', 'The Hextech trait grants its bonuses to all of your Champions. This does not increase your number of Hextech units. Gain a Sejuani.'),
	('605', 'Runic Shield II', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Vex.'),
	('606', 'Runic Shield III', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Swain.'),
	('604', 'Runic Shield I', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Swain.'),
	('748', 'Irresistible Charm', 'Debonair champions take @DamageReduction@% less damage. Gain a Leona.'),
	('804', 'Striker Heart', 'Your team counts as having 1 additional Striker. Gain a RekSai.'),
	('701', 'Protector Heart', 'Your team counts as having 1 additional Protector. Gain a Blitzcrank.'),
	('796', 'Debonair Heart', 'Your team counts as having 1 additional Debonair. Gain a Talon.'),
	('772', 'At Odds I', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('773', 'At Odds II', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('774', 'At Odds II', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('649', 'Stand United I', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('603', 'Academy Soul', 'Your team counts as having 2 additional Academics.'),
	('650', 'Stand United II', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('795', 'True Justice', 'Your Enforcers deal true damage to enemies below @HealthThreshold@% Health. Gain a Sejuani.'),
	('651', 'Stand United III', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('648', 'Exiles III', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('731', 'Phony Frontline', 'Gain @NumDummies@ Target Dummies.'),
	('647', 'Exiles II', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('657', 'Enforcer Soul', 'Your team counts as having 2 additional Enforcers. Gain @Gold@ gold.'),
	('723', 'True Twos', 'Gain @NumChamps@ random 2-star 2-cost units.'),
	('735', 'Thrill of the Hunt III', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('614', 'Assassin Heart', 'Your team counts as having 1 additional Assassin. Gain a Talon.'),
	('859', 'Smoke Bomb', 'The first time an Assassin drops to @HealthThreshold@% health, they briefly enter stealth, becoming untargetable and shedding all negative effects. Any excess damage is reduced by @DamageReduction@%. Gain a Talon.'),
	('734', 'Thrill of the Hunt II', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('733', 'Thrill of the Hunt I', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('724', 'Socialite Soul', 'Your team counts as having 2 additional Socialites.'),
	('797', 'Debonair Crown', 'Gain 2 Debonair Emblems.'),
	('871', 'TFT6_Augment_ExperimentalChallenger_Name', 'TFT6_Augment_ExperimentalChallenger_Desc'),
	('642', 'Armor Plating', 'Colossus become invulnerable for @InvulnDuration@ seconds when their Health drops to @HealthThreshold1@%. Gain a ChoGath.'),
	('743', 'Twinshot Soul', 'Your team counts as having 2 additional Twinshots. Gain @Gold@ gold.'),
	('801', 'Hextech Heart', 'Your team counts as having 1 additional Hextech. Gain a Swain.'),
	('610', 'Ascension', 'After @Delay@ seconds of combat, your units deal @DamageAmp@% more damage.'),
	('821', 'Challenger Unity', 'The Challenger trait grants its bonuses to all of your Champions. This does not increase your number of Challengers. Gain a Quinn.'),
	('600', 'Cram Session', 'After casting their first Ability, Academics restore @ManaRestorePercent@% of their maximum Mana.'),
	('703', 'Scoped Weapons', 'Double the hex range of your <b>ranged</b> units, and their attacks cannot miss.'),
	('715', 'March of Progress', 'Gain @Exp@ bonus experience points per round. You can no longer use gold to level up.'),
	('778', 'Verdant Veil', 'Your units are immune to crowd control effects for the first @Duration@ seconds of combat.'),
	('680', 'Innovator Heart', 'Your team counts as having 1 additional Innovator.'),
	('716', 'Sniper Crown', 'Gain 2 Sniper Emblems.'),
	('698', 'Pandoras Items', 'Gain a random component. At the start of each round, items on your bench are randomized (excluding Tacticians Crown, Spatula, and consumables).'),
	('874', 'Item Grab Bag I', 'Gain @NumItems@ random completed item.'),
	('611', 'Overpower', 'After every @NumAttacks@ attacks, Strikers gain @CritChance@% Critical Strike Chance for their next attack. Gain a Reksai.'),
	('683', 'Item Grab Bag II', 'Gain @NumItems@ random completed items and a Reforger.'),
	('856', 'Radiant Grab Bag', 'Gain @NumItems@ random Radiant item(s).'),
	('656', 'Enforcer Heart', 'Your team counts as having 1 additional Enforcer. Gain a Sejuani.'),
	('824', 'TFT6_Augment_CriticalThinking_Name', 'TFT6_Augment_CriticalThinking_Description'),
	('665', 'New Recruit', 'Gain +@MaxArmySizeIncrease@ maximum team size.'),
	('602', 'Academy Heart', 'Your team counts as having 1 additional Academic. Gain a Katarina.'),
	('836', 'Mutant Crown', 'Gain 2 Mutant Emblems.'),
	('676', 'Imperial Heart', 'Your team counts as having 1 additional Imperial. Gain a Swain.'),
	('660', 'Mutant Soul', 'Your team counts as having 2 additional Mutants.'),
	('845', 'So Small', 'Yordles gain @DodgeIncrease@% Dodge Chance. Gain a Corki.'),
	('687', 'Level Up!', 'When you buy experience points, gain an additional @XP@. You can now reach level 10.'),
	('639', 'Clockwork Crest', 'Gain a Clockwork Emblem and a Zilean.'),
	('609', 'Arcanist Soul', 'Your team counts as having 2 additional Arcanists.'),
	('666', 'Golden Ticket', 'Each time your Shop is refreshed, you have a @RerollPercent@% chance to gain a free refresh.'),
	('613', 'Hexnova', 'The first time a Hextech champion drops below @HealthThreshold@% Health, they increase nearby enemies maximum Mana by @PercentManaReave@% until they cast. Gain a Nocturne.'),
	('826', 'Treasure Trove I', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('714', 'Scrap Soul', 'Your team counts as having 2 additional Scraps. Gain @Gold@ gold.'),
	('860', 'TFT6_Augment_ColossusPummel_Name', 'TFT6_Augment_ColossusPummel_Description'),
	('709', 'Scholar Soul', 'Your team counts as having 2 additional Scholars. Gain @Gold@ gold.'),
	('685', 'Makeshift Armor II', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('829', 'Treasure Trove II', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('686', 'Makeshift Armor III', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('835', 'Treasure Trove III', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('832', 'Academy Crown', 'Gain 2 Academy Emblems.'),
	('718', 'Sharpshooter', 'Twinshots ranged attacks and Abilities can bounce once, dealing @BounceReduction@% less damage. Gain a Corki.'),
	('746', 'Windfall', 'Gain gold based on the number of augments you have now.<br>0 = @Augment1Gold@g, 1 = @Augment2Gold@g, 2 = @Augment3Gold@g'),
	('684', 'Makeshift Armor I', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('800', 'Hextech Crown', 'Gain 2 Hextech Emblems.'),
	('659', 'Mutant Heart', 'Your team counts as having 1 additional Mutant. Gain a RekSai.'),
	('862', 'Battlemage III', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('626', 'Challenger Crest', 'Gain a Challenger Emblem and a Quinn.'),
	('753', 'Battlemage II', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('752', 'Battlemage I', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('713', 'Scrap Heart', 'Your team counts as having 1 additional Scrap. Gain a Blitzcrank.'),
	('616', 'Band of Thieves', 'Gain @NumGloves@ Thiefs Gloves.'),
	('841', 'Chemtech Crown', 'Gain 2 Chemtech Emblems.'),
	('736', 'Titanic Force', 'Your units with more than @HealthThreshold@ maximum Health gain Attack Damage equal to @HealthPercent*100@% of their maximum Health.'),
	('857', 'En Garde', 'The first time an enemy is attacked by a Challenger, they are Disarmed for @DisarmDuration@ seconds. Gain a Warwick.'),
	('830', 'Imperial Crown', 'Gain 2 Imperial Emblems.'),
	('803', 'Striker Crown', 'Gain 2 Striker Emblems.'),
	('765', 'Second Wind I', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('868', 'Tiny Titans', 'Your Tactician heals @Heal@ Health, grows larger, and has @TooltipMaxHealth@ maximum Health.'),
	('767', 'Second Wind III', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('831', 'All For One', 'When an ally dies, they grant the Imperial Tyrant @MaxHealth@% of their maximum Health.'),
	('766', 'Second Wind II', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('754', 'Recombobulator', 'Champions on your board permanently transform into random champions that cost 1 more. Gain @NumRemovers@ Magnetic Removers.'),
	('712', 'Tinker', 'Gain a Magnetic Remover or Reforger every @Combats@ combat round(s) with the Scrap trait active.'),
	('784', 'Cybernetic Uplink II', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('785', 'Cybernetic Uplink III', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('628', 'Challenger Heart', 'Your team counts as having 1 additional Challenger. Gain a Quinn.'),
	('692', 'Gold Reserves', 'Mercenaries deal @PercentDamage*100@% more damage per @GoldIncrement@ gold you have (Maximum +@DamageCap@%). Gain a Quinn.'),
	('783', 'Cybernetic Uplink I', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('671', 'Bodyguard Soul', 'Your team counts as having 2 additional Bodyguards.'),
	('840', 'Syndicate Crest', 'Gain a Syndicate Emblem and a Zyra.'),
	('638', 'Broken Stopwatch', '@Delay@ seconds into combat, all enemies and non-Clockwork units are frozen in time for @StunDuration@ seconds. Gain a Zilean.'),
	('848', 'Sniper Crest', 'Gain a Sniper Emblem and an Ashe.'),
	('730', 'Syndicate Soul', 'Your team counts as having 2 additional Syndicates.'),
	('691', 'Mercenary Crest', 'Gain a Mercenary Emblem and @Gold@ gold.'),
	('747', 'Woodland Charm', 'At the start of combat, your highest Health Champion creates a @CloneHealth@ Health copy of themself (excluding items).'),
	('624', 'Celestial Blessing II', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('663', 'Featherweights III', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('625', 'Celestial Blessing III', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('662', 'Featherweights II', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('846', 'Featherweights I', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('782', 'Meditation III', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('623', 'Celestial Blessing I', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('781', 'Meditation II', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('719', 'Sniper Heart', 'Your team counts as having 1 additional Sniper. Gain an Ashe.'),
	('820', 'Meditation I', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('798', 'Debonair Crest', 'Gain a Debonair Emblem and a Syndra.'),
	('717', 'Snipers Nest', 'Snipers gain +@DamageAmp@% damage for each round fought from the same starting hex (Maximum +@MaxAmp@%). Gain an Ashe.'),
	('672', 'High End Shopping', 'Champions appear in your Shop as if you were 1 level higher. Gain @Gold@ gold.'),
	('682', 'Component Grab Bag', 'Gain @NumComponents@ random item components.'),
	('833', 'Built Different I', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('854', 'Future Sight', 'Know who you will fight next. Gain a Zephyr.'),
	('740', 'Built Different II', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('722', 'Share the Spotlight', 'Allies adjacent to a spotlight at the start of combat gain @PercentStats@% of its bonuses. Gain a Senna.'),
	('669', 'Stand Behind Me', 'Bodyguards Armor bonus is increased by @DefenseBonus@%. At the start of combat, Bodyguards grant @DefensePercent@% of their Armor bonus to non-Bodyguard allies directly behind them (does not stack). Gain a Blitzcrank.'),
	('741', 'Built Different III', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('855', 'Woodland Trinket', 'At the start of combat, your highest Attack Speed champion creates two @CloneHealth@ Health copies of themself (excluding items).'),
	('867', 'Threes Company', 'Gain @NumChamps@ random 3-cost champions.'),
	('876', 'TFT6_Augment_NeekoNeeko_Name', 'TFT6_Augment_NeekoNeeko_Description'),
	('732', 'Wise Spending', 'Gain @Gold@ gold. When you refresh your Shop, gain @XP@ experience point(s).'),
	('673', 'Hyper Roll', 'If you have less than @ThresholdGold@ gold at the end of a round, gain @Gold@ gold.'),
	('792', 'Ludens Echo I', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('727', 'One For All', 'When your Syndicates die, they grant your other Syndicates @Stats@ Attack Damage and Ability Power. Gain an Ashe.'),
	('794', 'Ludens Echo III', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('793', 'Ludens Echo II', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('694', 'Mercenary Heart', 'Your team counts as having 1 additional Mercenary.'),
	('853', 'High Five', 'Gain @NumChamps@ random 5-cost champions.'),
	('837', 'Arcane Crest', 'Gain an Arcanist Emblem and a Swain.'),
	('653', 'Ardent Censer', 'Allies healed or shielded by Enchanters gain @AS@% stacking Attack Speed for the rest of combat (maximum once every @CD@ seconds). Gain a Lulu.'),
	('729', 'Syndicate Heart', 'Your team counts as having 1 additional Syndicate. Gain a Zyra.'),
	('617', 'Binary Airdrop', 'Your champions equipped with 2 items temporarily gain a random completed item at the start of combat.'),
	('615', 'Assassin Soul', 'Your team counts as having 2 additional Assassins.'),
	('667', 'High Roller', 'Gain @NumDice@ Loaded Dice and @Gold@ gold.'),
	('601', 'Academy Crest', 'Gain an Academy Emblem and a Garen.'),
	('825', 'Protector Crown', 'Gain 2 Protector Emblems.'),
	('630', 'Chemtech Crest', 'Gain a Chemtech Emblem and a Warwick.'),
	('737', 'Ancient Archives', 'Gain @NumTomes@ Tome of Traits.'),
	('631', 'Instant Injection', 'Chemtechs now additionally trigger their bonuses at the start of combat. Gain a Warwick.'),
	('771', 'Jeweled Lotus', 'Magic and true damage from your units Abilities can critically strike. Your units gain @CritChance@% Critical Strike Chance.'),
	('612', 'Assassin Crown', 'Gain 2 Assassin Emblems.'),
	('696', 'Metabolic Accelerator', 'Your Tactician moves faster and heals @Heal@ Health after a PvP round.'),
	('807', 'Disintegrator I', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('728', 'Payday', 'After winning your combat, gain @BonusGold@ bonus gold for each surviving Syndicate. Gain an Ashe.'),
	('808', 'Disintegrator II', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('632', 'Chemical Overload I', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Warwick.'),
	('809', 'Disintegrator III', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('633', 'Chemical Overload II', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Zac.'),
	('789', 'Archangels Embrace I', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('634', 'Chemical Overload III', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Warwick.'),
	('790', 'Archangels Embrace', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('607', 'Spell Blade', 'After casting their Ability, Arcanists next attack deals bonus magic damage equal to @PercentAbilityPower@% of their Ability Power. Gain a Swain.'),
	('791', 'Archangels Embrace III', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('695', 'Mercenary Soul', 'Your team counts as having 2 additional Mercenaries.'),
	('839', 'Golden Gifts I', 'Gain @NumGoldOrbs@ golden and @NumGrayOrbs@ gray loot orb(s).'),
	('702', 'Protector Soul', 'Your team counts as having 2 additional Protectors.'),
	('641', 'Clockwork Soul', 'Your team counts as having 2 additional Clockworks. Gain @Gold@ gold.'),
	('866', 'The Golden Egg', 'Gain a massive golden egg that hatches in @EggTurns@ turns.'),
	('827', 'Golden Gifts II', 'Gain @NumGoldOrbs@ golden and @NumGrayOrbs@ gray loot orb(s).'),
	('745', 'Weakspot I', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('872', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('849', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('710', 'Junkyard', 'Gain a random component every @Combats@ combat rounds with the Scrap Trait active. Gain an Ezreal.'),
	('828', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('679', 'Self Repair', 'When the Innovation dies, it will become untargetable and repair itself if an Innovator is still alive. Gain a Zilean.'),
	('760', 'Thieving Rascals', 'Free Yordles from the portal have a @ItemChance@% chance to arrive holding an item component. Gain a Lulu.'),
	('708', 'Scholar Heart', 'Your team counts as having 1 additional Scholar. Gain a Zyra.'),
	('688', 'Knifes Edge I', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('635', 'Chemtech Heart', 'Your team counts as having 1 additional Chemtech. Gain a Warwick.'),
	('690', 'Knifes Edge III', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('689', 'Knifes Edge II', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('725', 'Sunfire Board', 'At the start of combat, burn all enemies for @TotalBurnPercent@% of their maximum Health over @Duration@ seconds and reduce healing received by @GrievousWoundsPercent@%.'),
	('668', 'Bodyguard Crest', 'Gain a Bodyguard Emblem and a Darius.'),
	('661', 'Tri Force III', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('861', 'Cutthroat', 'Assassins Mana Reave the first unit they attack, increasing their maximum Mana by @ManaReavePercent@% until they cast. Gain a Talon.'),
	('851', 'Tri Force II', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('863', 'Tri Force I', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('749', 'Backfoot I', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('750', 'Backfoot II', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('802', 'Striker Crest', 'Gain a Striker Emblem and a Reksai.'),
	('704', 'Rich Get Richer', 'Gain @Gold@ gold. Your maximum interest is increased to @InterestCap@.'),
	('751', 'Backfoot III', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('810', 'Divine Intervention', 'Gain a Radiant Blessing loot orb.'),
	('755', 'Radiant Relics', 'Open an Armory and choose 1 of @ArmoryChoiceCount@ unique Radiant items.'),
	('654', 'Enchanter Heart', 'Your team counts as having 1 additional Enchanter. Gain a Lulu.'),
	('707', 'Lifelong Learning', 'Scholars permanently gain @AP@ Ability Power after each combat, and an additional @BonusAP@ if they survived. Gain a Syndra.'),
	('619', 'Bruiser Crest', 'Gain a Bruiser Emblem and a Sejuani.'),
	('864', 'Very VIP', 'When an ally dies, they grant the Debonair VIP @MaxHealth@% of their maximum Health for the rest of combat. Gain a Syndra.'),
	('678', 'Imperial Soul', 'Your team counts as having 2 additional Imperials.'),
	('658', 'Mutant Crest', 'Gain a Mutant Emblem and a Kassadin.'),
	('834', 'Socialite Heart', 'Your team counts as having 1 additional Socialite. '),
	('756', 'Blue Battery I', 'After casting their Ability, your units restore @ManaRestore@ Mana.'),
	('674', 'Dual Rule', 'There are now @Tyrants@ Imperial Tyrants.'),
	('758', 'Blue Battery II', 'After casting their Ability, your units restore @ManaRestore@ Mana.'),
	('699', 'Portable Forge', 'Open an Armory and choose 1 of @ArmoryChoiceCount@ unique Artifacts crafted by Ornn.'),
	('838', 'Assassin Crest', 'Gain an Assassin Emblem and a Talon.'),
	('843', 'Challenger Crown', 'Gain 2 Challenger Emblems.'),
	('711', 'Scrap Crest', 'Gain a Scrap Emblem and a Blitzcrank.'),
	('847', 'Bodyguard Crown', 'Gain 2 Bodyguard Emblems.'),
	('681', 'Innovator Soul', 'Your team counts as having 2 additional Innovators.'),
	('622', 'Calculated Loss', 'After losing your combat, gain @Gold@ gold and a free Shop refresh.'),
	('842', 'Bruiser Crown', 'Gain 2 Bruiser Emblems.'),
	('621', 'Bruiser Soul', 'Your team counts as having 2 additional Bruisers.'),
	('700', 'Protector Crest', 'Gain a Protector Emblem and a Garen.'),
	('664', 'First Aid Kit', 'All healing and shielding on your units is increased by @HealShieldIncrease*100@%.'),
	('762', 'Electrocharge I', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('768', 'Arcane Nullifier I', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('636', 'Chemtech Soul', 'Your team counts as having 2 additional Chemtechs.'),
	('764', 'Electrocharge III', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('770', 'Arcane Nullifier III', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('763', 'Electrocharge II', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('769', 'Arcane Nullifier II', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('742', 'Twinshot Heart', 'Your team counts as having 1 additional Twinshot. Gain a Corki.'),
	('655', 'Enchanter Soul', 'Your team counts as having 2 additional Enchanters. Gain @Gold@ gold.'),
	('865', 'Stored Power', 'Your Hextech champions permanently gain @AP@ Ability Power each time they are hit by your Hexcores pulses. Gain a Swain.'),
	('869', 'Double Trouble II', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('852', 'Phalanx III', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('870', 'Double Trouble III', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('780', 'Phalanx II', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('779', 'Phalanx I', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('645', 'Cybernetic Implants III', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('739', 'Double Trouble I', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('744', 'Underdogs', 'Whenever your team has fewer units alive than your opponent, your units regenerate @MissingHeal@% Health each second (maximum: @HealCap@).'),
	('644', 'Cybernetic Implants II', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('643', 'Cybernetic Implants I', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('806', 'Weakspot III', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('805', 'Weakspot II', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('652', 'Dominance', 'After winning your player combat, gain @Gold@ bonus gold for every @PerSurvivingUnit@ surviving units.'),
	('646', 'Exiles', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('697', 'Unstable Evolution', 'Mutants randomly gain one of the following when they reach 2 star: @BonusHP@ Health, @BonusAS@% Attack Speed, @BonusAD@ Attack Damage, or @BonusAP@ Ability Power. These bonuses stack. Gain a RekSai.'),
	('618', 'Shrug It Off', 'Bruisers regenerate @RegenPerTick@% of their maximum Health each second. Gain a Sejuani.'),
	('640', 'Clockwork Heart', 'Your team counts as having 1 additional Clockwork. Gain a Zilean.'),
	('812', 'Keepers II', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('720', 'Sniper Soul', 'Your team counts as having 2 additional Snipers.'),
	('813', 'Keepers III', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('738', 'Trade Sector', 'Gain a free Shop refresh each round.'),
	('811', 'Keepers I', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('844', 'Arcanist Crown', 'Gain 2 Arcanist Emblems.'),
	('721', 'Duet', 'Summon 1 additional Socialite spotlight. Spotlighted units gain @BonusHealth@ Health. Gain a Senna.'),
	('627', 'Concussive Blows', 'Strikers critical strikes stun their target for @StunDuration@ second(s). Each target can only be stunned once every @StunCD@ seconds. Gain a RekSai.'),
	('705', 'Salvage Bin', 'Gain a random completed item. Selling champions breaks apart their full items into components (excluding Tacticians Crown).'),
	('822', 'Chemtech Unity', 'The Chemtech trait grants its bonuses to all of your Champions. This does not increase your number of Chemtech units. Gain a Warwick.'),
	('620', 'Bruiser Heart', 'Your team counts as having 1 additional Bruiser. Gain a Sejuani.'),
	('670', 'Bodyguard Heart', 'Your team counts as having 1 additional Bodyguard. Gain a Blitzcrank.'),
	('629', 'Challenger Soul', 'Your team counts as having 2 additional Challengers.'),
	('799', 'Hextech Crest', 'Gain a Hextech Emblem and a Nocturne.'),
	('850', 'Future Sight II', 'Know who you will fight next. Gain a Radiant Zephyr.'),
	('788', 'Cybernetic Shell III', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('787', 'Cybernetic Shell II', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('786', 'Cybernetic Shell I', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('873', 'TFT6_Augment_InfinityCane_Name', 'TFT6_Augment_InfinityCane_Description'),
	('608', 'Arcanist Heart', 'Your team counts as having 1 additional Arcanist. Gain a Swain.'),
	('637', 'Clear Mind', 'If you have no champions on your bench at the end of a round, gain @XP@ experience points.'),
	('675', 'Imperial Crest', 'Gain an Imperial Emblem and a Swain.');
