INSERT INTO units (char_id, cname, cost) 
	 VALUES 	('TFT6_Leona', 'Leona', '3'),
	('TFT6_Singed', 'Singed', '1'),
	('TFT6_Warwick', 'Warwick', '2'),
	('TFT6_Zac', 'Zac', '3'),
	('TFT6_Viktor', 'Viktor', '5'),
	('TFT6_Camille', 'Camille', '1'),
	('TFT6_Zilean', 'Zilean', '2'),
	('TFT6_Orianna', 'Orianna', '4'),
	('TFT6_Jhin', 'Jhin', '4'),
	('TFT6_MissFortune', 'Miss Fortune', '3'),
	('TFT6_Illaoi', 'Illaoi', '1'),
	('TFT6_Gangplank', 'Gangplank', '3'),
	('TFT6_TahmKench', 'Tahm Kench', '5'),
	('TFT6_Seraphine', 'Seraphine', '4'),
	('TFT6_Zyra', 'Zyra', '2'),
	('TFT6_Darius', 'Darius', '1'),
	('TFT6b_Vi', 'Vi', '4'),
	('TFT6_Caitlyn', 'Caitlyn', '1'),
	('TFT6_Jayce', 'Jayce', '5'),
	('TFT6_Malzahar', 'Malzahar', '3'),
	('TFT6_ChoGath', 'ChoGath', '3'),
	('TFT6_Galio', 'Galio', '5'),
	('TFT6_Ezreal', 'Ezreal', '1'),
	('TFT6_Blitzcrank', 'Blitzcrank', '2'),
	('TFT6_Ekko', 'Ekko', '3'),
	('TFT6_Ziggs', 'Ziggs', '1'),
	('TFT6_Jinx', 'Jinx', '5'),
	('TFT6_Poppy', 'Poppy', '1'),
	('TFT6_Lulu', 'Lulu', '2'),
	('TFT6_Vex', 'Vex', '3'),
	('TFT6_Kassadin', 'Kassadin', '1'),
	('TFT6_Tibbers', 'Mechanical Bear', '5'),
	('TFT6_Quinn', 'Quinn', '2'),
	('TFT6_Talon', 'Talon', '2'),
	('TFT6_Kaisa', 'KaiSa', '5'),
	('TFT6_Braum', 'Braum', '4'),
	('TFT6_MalzaharVoidling', 'Mechanical Scarab', '8'),
	('TFT6_MercenaryChest', 'Mercenary Chest', '8'),
	('TFT6_Veigar', 'Veigar', '5'),
	('TFT6_HexTechDragon', 'Mechanical Dragon', '5'),
	('TFT6_TheGoldenEgg', 'The Golden Egg', '5'),
	('TFT6_Nocturne', 'Nocturne', '1'),
	('TFT6_Brand', 'Brand', '1'),
	('TFT6_Annie', 'Annie', '8'),
	('TFT6_Sejuani', 'Sejuani', '2'),
	('TFT6_Syndra', 'Syndra', '2'),
	('TFT6_RekSai', 'RekSai', '2'),
	('TFT6_Ashe', 'Ashe', '2'),
	('TFT6_Sivir', 'Sivir', '4'),
	('TFT6_Tryndamere', 'Tryndamere', '3'),
	('TFT6_Gnar', 'Gnar', '3'),
	('TFT6_Morgana', 'Morgana', '3'),
	('TFT6_Lucian', 'Lucian', '3'),
	('TFT6_Draven', 'Draven', '4'),
	('TFT6_KhaZix', 'KhaZix', '4'),
	('TFT6_Ahri', 'Ahri', '4'),
	('TFT6_Irelia', 'Irelia', '4'),
	('TFT6_Corki', 'Corki', '2'),
	('TFT6_Senna', 'Senna', '3'),
	('TFT6_Alistar', 'Alistar', '4'),
	('TFT6_Renata', 'Renata Glasc', '4'),
	('TFT6_Silco', 'Silco', '5'),
	('TFT6_Zeri', 'Zeri', '5'),
	('TFT6_Twitch', 'Twitch', '1'),
	('TFT6_Swain', 'Swain', '2'),
	('TFT6_JarvanIV', 'Jarvan IV', '1');
