INSERT INTO items (item_id, iname, descrip) 
	 VALUES 	('119', 'tft_item_name_StarGuardianSpatulaItem', 'tft_item_description_StarGuardianSpatulaItem'),
	('135', 'tft_item_name_UmbralGlaive', 'tft_item_description_SlicerSpatulaItem'),
	('117', 'tft_item_name_InfiltratorSpatulaItem', 'tft_item_description_InfiltratorSpatulaItem'),
	('116', 'tft_item_name_CelestialSpatulaItem', 'tft_item_description_CelestialSpatulaItem'),
	('120', 'Protectors Chestguard', 'The holder gains the Protector trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('118', 'tft_item_name_DarkStarSpatulaItem', 'tft_item_description_DarkStarSpatulaItem'),
	('136', 'tft_item_name_RebelSpatulaItem', 'tft_item_description_RebelSpatulaItem'),
	('127', 'tft_item_name_DemolitionistSpatulaItem', 'tft_item_description_DemolitionistSpatulaItem'),
	('128', 'Battlecast Plating', 'The wearer gains the Battlecast trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('131', 'Berserkers Axe', 'The wearer is also a Berserker.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('122', 'Infernos Cinder', 'The wearer is also an Inferno.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('107', 'TFT_item_name_BladeOfTheRuinedKing', 'TFT_item_description_BladeOfTheRuinedKing'),
	('129', 'tft_item_name_SteelSphere', 'tft_item_description_SteelSphere'),
	('134', 'Wardens Mail', 'The wearer is also a Warden.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('133', 'TFT_item_name_FrozenMallet', 'TFT_item_description_FrozenMallet'),
	('132', 'Talisman of Light', 'The wearer is also Light.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('130', 'Youmuus Ghostblade', 'The holder is also an Assassin.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('108', 'Sword of the Divine', 'The holder gains the Divine trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('114', 'Vanguards Cuirass', 'The holder gains the Vanguard trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('109', 'Duelists Zeal', 'The holder gains the Duelist trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('121', 'Aspect of Dusk', 'The holder gains the Dusk trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('110', 'Warlords Banner', 'The wearer gains the Warlord trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('113', 'Mages Hat', 'The holder gains the Mage trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('115', 'Spirit of the Dragon', 'The holder gains the Dragonsoul trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('112', 'Youmuus Ghostblade', 'The wearer gains the Assassin trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('111', 'Elderwood Sprout', 'The holder gains the Elderwood trait.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('1046', 'Chalice of Malice', 'When combat begins, all of the holders allies within @HexRange@ hex in the same row gain %i:scaleAP% <TFTShadowItemBonus>@BonusAP@ Ability Power</TFTShadowItemBonus> for the rest of combat. <TFTShadowItemPenalty>The holder loses %i:scaleAP% @APLost@ Ability Power instead of gaining any.</TFTShadowItemPenalty>'),
	('1014', 'Spectral Spear of Shojin', 'The holders attacks restore %i:scaleMana% <TFTShadowItemBonus>@FlatManaRestore@ additional Mana.</TFTShadowItemBonus>'),
	('1044', 'Very Dark Blue Buff', 'After casting their Ability, the holder gains %i:scaleMana% <TFTShadowItemBonus>@PostCastMana@</TFTShadowItemBonus> Mana.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1017', 'Zekes Bleak Herald', 'When combat begins, the holder <TFTShadowItemPenalty>reduces the Attack Speed of all allies within @HexRange@ hexes in the same row by %i:scaleAS% @AttackSpeedReduction@%.</TFTShadowItemPenalty> <TFTShadowItemBonus>The holder then gains %i:scaleAS% @AttackSpeed@% Attack Speed for each affected ally.</TFTShadowItemBonus>'),
	('1056', 'Gargoyle Stoneplate Of Immortality', 'The holder heals themself for @HealingPerEnemy@ Health every @SecondsBetweenHeals@ seconds for each unit targeting them.'),
	('1055', 'Refracted Bramble Vest', 'Grants %i:scaleArmor% @TooltipDisplayArmor@ bonus Armor (including components).'),
	('1033', 'Rabadons Caustic Deathcap', 'Grants %i:scaleAP% <TFTShadowItemBonus>@TooltipDisplayAP@</TFTShadowItemBonus> bonus Ability Power (including components). '),
	('1008', 'Shadow Spatula', 'It must do <i>something <TFTShadowItemBonus>evil</TFTShadowItemBonus></i>...'),
	('1006', 'Shadow Cloak', '%i:scaleMR% +@MagicResist@ Magic Resist'),
	('1024', 'Statikk Stiletto', '<TFTShadowItemBonus>Every other</TFTShadowItemBonus> attack from the holder unleashes chain lightning that strikes @1StarBounces@ enemies, dealing @Damage@ magic damage and reducing their Magic Resist by @MRShred@% for @MRShredDuration@ seconds. '),
	('1047', 'Sacrificial Redemption', 'The holder radiates an aura to <TFTShadowItemBonus>all allies on the board</TFTShadowItemBonus> except themself, and heals them for <TFTShadowItemPenalty>@MissingHealthHeal@%</TFTShadowItemPenalty> of their missing Health every @HealTickRate@ seconds.'),
	('1069', 'Caustic Quicksilver', 'The holder gains immunity to crowd control <TFTShadowItemBonus>for the entirety of combat</TFTShadowItemBonus>.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1002', 'Shadow Bow', '%i:scaleAS% +@AS@ Attack Speed'),
	('1035', 'Locket of the Silver Lunari', 'When combat begins, the holder and all allies within @HexRange@ hexes in the same row gain <TFTShadowItemBonus>@BonusDefenses@ bonus Armor and Magic Resist</TFTShadowItemBonus>.'),
	('1049', 'Hand of Vengeance', '<TFTShadowItemBonus>At the beginning of combat, the holder gains both of the following:</TFTShadowItemBonus><li>+@BonusAD@ Attack Damage and +@BonusSP@ Ability Power.</li> <li>Attacks and Abilities heal for @TraitMultiplier@% of damage dealt.</li><br><TFTShadowItemPenalty>These bonuses expire after each takedown, and renew on the next.</TFTShadowItemPenalty>'),
	('1067', 'Turbulent Zephyr', 'When combat begins, the holder summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for <TFTShadowItemBonus>@BanishDuration@ seconds.</TFTShadowItemBonus><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1019', 'Sacrificial Infinity Edge', 'Grants @CritChance@% Critical Strike Chance (including components). Each point of Critical Strike Chance above 100% becomes +@BonusCritDmgPerCritAbove100@% Critical Strike Damage. <br><br><TFTShadowItemBonus>The holder also gains @BonusCritDamage@% Critical Strike Damage.</TFTShadowItemBonus><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1066', 'Refracted Dragons Claw', 'Reduces incoming magic damage by @MagicReduction@%.<br><br><TFTShadowItemBonus>Negates bonus damage from incoming critical hits.</TFTShadowItemBonus>'),
	('1029', 'Final Whisper', 'The holders attacks and abilities reduce the targets Armor <TFTShadowItemBonus>and Magic Resist</TFTShadowItemBonus> by @ArmorMRReductionPercent@% for the rest of combat.<br><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1034', 'Archdemons Staff Of Immortality', 'Each time the holder casts their Ability, they gain empty maximum Health equal to @ManaRatio@% of their maximum Mana. The holder then heals for that amount.<br>'),
	('1039', 'Sacrificial Gauntlet', 'The holder gains @CritDamageAmp@% Critical Strike Damage, and magic and true damage from their Ability can critically strike. <br><br><TFTShadowItemBonus>The first time they cast their Ability each combat, they gain an additional @BonusCritChance@% Critical Strike Chance for the remainder of combat (applies to that Ability cast).</TFTShadowItemBonus>'),
	('1016', 'Riskthirster', 'Physical damage heals the holder for @Lifesteal@% of the damage dealt. <TFTShadowItemBonus>Each time the holder heals to @HealthThresholdPercent@% Health, they gain @BonusAS@% Attack Speed for @BonusASDuration@ seconds.</TFTShadowItemBonus> <TFTShadowItemPenalty>The holder takes @HealthLossPercent@% of their maximum Health in true damage at the beginning of combat or upon being equipped.</TFTShadowItemPenalty>'),
	('1007', 'Shadow Belt', '%i:scaleHealth% +@Health@ Health'),
	('1011', 'Caustic Deathblade', 'Contributing to a kill grants the holder %i:scaleAD% <TFTShadowItemBonus>@ADPerStack@ Attack Damage</TFTShadowItemBonus> for the rest of combat. This effect can stack any number of times (starting at @StartingStacks@).'),
	('1099', 'Tricksters Gloves', 'At the beginning of each planning phase, the holder equips 2 temporary items. These are always full shadow items.<br><br><tftitemrules>[Consumes Three Item Slots]</tftitemrules>'),
	('1022', 'Rapid Deathcannon', 'Increases the holders Attack Range by @HexRangeIncrease@ hex. Additionally, the holder gains %i:scaleAS% <TFTShadowItemBonus>+@BonusAS@% bonus Attack Speed</TFTShadowItemBonus> <TFTShadowItemPenalty>when there are no enemies within @HexRequirement@ hex.</TFTShadowItemPenalty><br><br>The holders attacks can no longer miss.<br><br>'),
	('1003', 'Shadow Rod', '%i:scaleAP% +@AP@ Ability Power'),
	('1025', 'Titans Revenge', '@PercentDamage@% of incoming damage is stored. Every @SecondsBetweenProcs@ seconds, the holders next attack unleashes this stored damage as true damage.'),
	('1045', 'Frozen Dark Heart', 'Reduces the Attack Speed of all enemies within @HexRadius@ hexes by <TFTShadowItemBonus>@AttackSpeedSlow@%</TFTShadowItemBonus>.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1036', 'Ionic Dark-Spark', 'Enemies within @HexRange@ hexes have their Magic Resist reduced by @MRShred@%. When they cast an Ability, they are zapped taking magic damage equal to @ManaRatio@% of their max Mana.'),
	('1057', 'Eclipse Cape', 'Every <TFTShadowItemBonus>@ICD@ second(s)</TFTShadowItemBonus>, a random enemy within <TFTShadowItemBonus>@HexRange@ hexes</TFTShadowItemBonus> is burned for @BurnPercent@% of their maximum Health as true damage over @BurnDuration@ seconds. Any healing they receive is reduced by @GrievousWoundsPercent@%.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1059', 'Dark Shroud of Stillness', 'When combat begins, the holder shoots a beam straight ahead <TFTShadowItemPenalty>and behind</TFTShadowItemPenalty> that delays affected enemies first ability cast, increasing their maximum Mana by <TFTShadowItemBonus>@CostIncrease@%</TFTShadowItemBonus> until they cast.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1026', 'Runaans Untamed Hurricane ', 'The holders attacks fire bolts at <TFTShadowItemBonus>@AdditionalTargets@ nearby enemies</TFTShadowItemBonus>, dealing <TFTShadowItemPenalty>@MultiplierForDamage@% of the holders Attack Damage.</TFTShadowItemPenalty> These bolts can critically strike but do not apply on-hit effects. '),
	('1088', 'Force of Darkness', 'The holders team gains <TFTShadowItemBonus>+@MaxArmySizeIncrease@</TFTShadowItemBonus> maximum team size, but <TFTShadowItemPenalty>the players Little Legend takes +@PercentDamageIncrease@% damage after losing a battle</TFTShadowItemPenalty>.'),
	('1015', 'Fallen Guardian Angel', 'Prevents the holders first death, placing them in stasis instead. After @StasisDuration@ seconds, they return with <TFTShadowItemBonus>@HealthRestorePercent@% Health</TFTShadowItemBonus> and shed all negative effects.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1005', 'Shadow Vest', '%i:scaleArmor% +@Armor@ Armor'),
	('1004', 'Shadow Tear', '%i:scaleMana% +@Mana@ Mana'),
	('1009', 'Shadow Gloves', '+@CritChance@ Critical Strike Chance<br>+@DodgeChance@ Dodge Chance'),
	('1012', 'Spectral Giantslayer', 'The holders Abilities and attacks do @SmallBonusPct@% bonus damage. If the target has more than @HealthThreshold@ maximum Health, the bonus increases to @LargeBonusPct@%.'),
	('1027', 'Unstable ZzRot Portal', 'At the start of combat, the holder taunts enemies within @HexRadius@ hexes.<br><br>When the holder dies, an Unstable Voidspawn with <TFTShadowItemPenalty>@ZombieHealth@ Health</TFTShadowItemPenalty> arises and taunts enemies again. When it dies <TFTShadowItemBonus>it deals @ExplosionDamage@ true damage to enemies within @ExplosionHexRange@ hex(es).</TFTShadowItemBonus><br><br>Voidspawns that arise from summoned units are @SummonedStatReduction@% effective.'),
	('555', 'tft_item_name_RadiantSpatula', 'tft_item_description_RadiantSpatula'),
	('1077', 'Warmogs Sacrificial Armor', 'Grants %i:scaleHealth% <TFTShadowItemBonus>@TooltipDisplayHealth@ bonus Health</TFTShadowItemBonus> (including components).'),
	('1013', 'Hextech Gunblade Of Immortality', 'The holders magic and true damage from Abilities heals the ally with lowest percent Health for <TFTShadowItemBonus>@OmniVamp@% of the damage dealt.</TFTShadowItemBonus> <TFTShadowItemPenalty>This heal cannot affect the holder.</TFTShadowItemPenalty>'),
	('1079', 'Banshees Claw', 'When combat begins, the holder and all allies within @HexRange@ hexes in the same row gain a shield that blocks the first enemy Ability.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1023', 'Guinsoos Sacrificial Rageblade', 'Attacks grant <TFTShadowItemBonus>+@AttackSpeedPerStack@%</TFTShadowItemBonus> bonus Attack Speed for the rest of combat. The bonus Attack Speed can stack any number of times.'),
	('1037', 'Mor-evil-lonomicon', 'When the holder deals magic or true damage with their Ability, they burn the target, dealing <TFTShadowItemBonus>@BurnPercent@% of the targets maximum Health</TFTShadowItemBonus> as true damage over @BurnDuration@ seconds, and reducing healing by @GrievousWoundsPercent@% for the duration of the burn.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1001', 'Shadow Sword', '%i:scaleAD% +@AD@ Attack Damage'),
	('106', 'Ironclad Emblem', 'The holder gains the Ironclad trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('104', 'Redeemed Emblem', 'The holder gains the Redeemed trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1148', 'Coven Emblem', 'The holder gains the Coven trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1195', 'Cannoneer Emblem', 'The holder gains the Cannoneer trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('123', 'Skirmisher Emblem', 'The holder gains the Skirmisher trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('518', 'tft_item_name_Set5Skirmisher_RadiantSpat', 'tft_item_description_Set5Skirmisher_RadiantSpat'),
	('2118', 'tft_item_name_Set5Forgotten_RadiantSpat', 'tft_item_description_Set5Forgotten_RadiantSpat'),
	('105', 'Spellweaver Emblem', 'The holder gains the Spellweaver trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2178', 'tft_item_name_Set5Nightbringer_RadiantSpat', 'tft_item_description_Set5Nightbringer_RadiantSpat'),
	('1158', 'Cavalier Emblem', 'The holder gains the Cavalier trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('538', 'tft_item_name_Set5Spellweaver_RadiantSpat', 'tft_item_description_Set5Spellweaver_RadiantSpat'),
	('124', 'Dawnbringer Emblem', 'The holder gains the Dawnbringer trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('568', 'tft_item_name_Set5Redeemed_RadiantSpat', 'tft_item_description_Set5Redeemed_RadiantSpat'),
	('125', 'Assassin Emblem', 'The holder gains the Assassin trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2168', 'tft_item_name_Set5Revenant_RadiantSpat', 'tft_item_description_Set5Revenant_RadiantSpat'),
	('2189', 'tft_item_name_Set5Abomination_RadiantSpat', 'tft_item_description_Set5Abomination_RadiantSpat'),
	('548', 'tft_item_name_Set5Renewer_RadiantSpat', 'tft_item_description_Set5Renewer_RadiantSpat'),
	('1128', 'Hellion Emblem', 'The holder gains the Hellion trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1178', 'Nightbringer Emblem', 'The holder gains the Nightbringer trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('1193', 'Brawler Emblem', 'The holder gains the Brawler trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('1192', 'Invoker Emblem', 'The holder gains the Invoker trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('126', 'Renewer Emblem', 'The holder gains the Renewer trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('1138', 'Dragonslayer Emblem', 'The holder gains the Dragonslayer trait.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('1118', 'Forgotten Emblem', 'The holder gains the Forgotten trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('589', 'tft_item_name_Set5Assassin_RadiantSpat', 'tft_item_description_Set5Assassin_RadiantSpat'),
	('1190', 'Ranger Emblem', 'The holder gains the Ranger trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('1189', 'Abomination Emblem', 'The holder gains the Abomination trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('558', 'tft_item_name_Set5Ironclad_RadiantSpat', 'tft_item_description_Set5Ironclad_RadiantSpat'),
	('1196', 'Knight Emblem', 'The holder gains the Knight trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('1197', 'Mystic Emblem', 'The holder gains the Mystic trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('578', 'tft_item_name_Set5Dawnbringer_RadiantSpat', 'tft_item_description_Set5Dawnbringer_RadiantSpat'),
	('528', 'tft_item_name_Set5Legionnaire_RadiantSpat', 'tft_item_description_Set5Legionnaire_RadiantSpat'),
	('2128', 'tft_item_name_Set5Hellion_RadiantSpat', 'tft_item_description_Set5Hellion_RadiantSpat'),
	('103', 'Legionnaire Emblem', 'The holder gains the Legionnaire trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2158', 'tft_item_name_Set5Cavalier_RadiantSpat', 'tft_item_description_Set5Cavalier_RadiantSpat'),
	('1191', 'Draconic Emblem', 'The holder gains the Draconic trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('2148', 'tft_item_name_Set5Coven_RadiantSpat', 'tft_item_description_Set5Coven_RadiantSpat'),
	('1194', 'Sentinel Emblem', 'The holder gains the Sentinel trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('1168', 'Revenant Emblem', 'The holder gains the Revenant trait.<br><br><tftitemrules>[Unique - only one per champion.<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('693', 'Pirates', 'Mercenary units have a @Chance@% chance to drop @Gold@ gold when they kill an enemy. Gain a Quinn.'),
	('706', 'Scholar Crest', 'Gain a Scholar Emblem and a Zyra.'),
	('776', 'Break Even II', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('858', 'Four Score', 'Gain @NumChamps@ random 4-cost champions.'),
	('777', 'Break Even III', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('877', 'TFT6_Augment_BrawlerHPVeteran_Name', 'TFT6_Augment_BrawlerHPVeteran_Description'),
	('726', 'Syndicate Crown', 'Gain 2 Syndicate Emblems.'),
	('775', 'Break Even I', 'Your 2 and 4-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('823', 'Hextech Unity', 'The Hextech trait grants its bonuses to all of your Champions. This does not increase your number of Hextech units. Gain a Sejuani.'),
	('605', 'Runic Shield II', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Vex.'),
	('606', 'Runic Shield III', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Swain.'),
	('604', 'Runic Shield I', 'Arcanists start combat with a shield equal to @APShield@% of their Ability Power for @ShieldDuration@ seconds. Gain a Swain.'),
	('748', 'Irresistible Charm', 'Debonair champions take @DamageReduction@% less damage. Gain a Leona.'),
	('804', 'Striker Heart', 'Your team counts as having 1 additional Striker. Gain a RekSai.'),
	('701', 'Protector Heart', 'Your team counts as having 1 additional Protector. Gain a Blitzcrank.'),
	('796', 'Debonair Heart', 'Your team counts as having 1 additional Debonair. Gain a Talon.'),
	('772', 'At Odds I', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('773', 'At Odds II', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('774', 'At Odds II', 'Your 1, 3, and 5-cost units gain @Stats@ Attack Damage and Ability Power.'),
	('649', 'Stand United I', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('603', 'Academy Soul', 'Your team counts as having 2 additional Academics.'),
	('650', 'Stand United II', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('795', 'True Justice', 'Your Enforcers deal true damage to enemies below @HealthThreshold@% Health. Gain a Sejuani.'),
	('651', 'Stand United III', 'Your units gain @Resists@ Attack Damage and Ability Power per Trait active across your army.'),
	('648', 'Exiles III', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('731', 'Phony Frontline', 'Gain @NumDummies@ Target Dummies.'),
	('647', 'Exiles II', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('657', 'Enforcer Soul', 'Your team counts as having 2 additional Enforcers. Gain @Gold@ gold.'),
	('723', 'True Twos', 'Gain @NumChamps@ random 2-star 2-cost units.'),
	('735', 'Thrill of the Hunt III', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('614', 'Assassin Heart', 'Your team counts as having 1 additional Assassin. Gain a Talon.'),
	('859', 'Smoke Bomb', 'The first time an Assassin drops to @HealthThreshold@% health, they briefly enter stealth, becoming untargetable and shedding all negative effects. Any excess damage is reduced by @DamageReduction@%. Gain a Talon.'),
	('734', 'Thrill of the Hunt II', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('733', 'Thrill of the Hunt I', 'Your units heal @MissingHPHeal@ Health on kill.'),
	('724', 'Socialite Soul', 'Your team counts as having 2 additional Socialites.'),
	('797', 'Debonair Crown', 'Gain 2 Debonair Emblems.'),
	('871', 'TFT6_Augment_ExperimentalChallenger_Name', 'TFT6_Augment_ExperimentalChallenger_Desc'),
	('642', 'Armor Plating', 'Colossus become invulnerable for @InvulnDuration@ seconds when their Health drops to @HealthThreshold1@%. Gain a ChoGath.'),
	('743', 'Twinshot Soul', 'Your team counts as having 2 additional Twinshots. Gain @Gold@ gold.'),
	('801', 'Hextech Heart', 'Your team counts as having 1 additional Hextech. Gain a Swain.'),
	('610', 'Ascension', 'After @Delay@ seconds of combat, your units deal @DamageAmp@% more damage.'),
	('821', 'Challenger Unity', 'The Challenger trait grants its bonuses to all of your Champions. This does not increase your number of Challengers. Gain a Quinn.'),
	('600', 'Cram Session', 'After casting their first Ability, Academics restore @ManaRestorePercent@% of their maximum Mana.'),
	('703', 'Scoped Weapons', 'Double the hex range of your <b>ranged</b> units, and their attacks cannot miss.'),
	('715', 'March of Progress', 'Gain @Exp@ bonus experience points per round. You can no longer use gold to level up.'),
	('778', 'Verdant Veil', 'Your units are immune to crowd control effects for the first @Duration@ seconds of combat.'),
	('680', 'Innovator Heart', 'Your team counts as having 1 additional Innovator.'),
	('716', 'Sniper Crown', 'Gain 2 Sniper Emblems.'),
	('698', 'Pandoras Items', 'Gain a random component. At the start of each round, items on your bench are randomized (excluding Tacticians Crown, Spatula, and consumables).'),
	('874', 'Item Grab Bag I', 'Gain @NumItems@ random completed item.'),
	('611', 'Overpower', 'After every @NumAttacks@ attacks, Strikers gain @CritChance@% Critical Strike Chance for their next attack. Gain a Reksai.'),
	('683', 'Item Grab Bag II', 'Gain @NumItems@ random completed items and a Reforger.'),
	('856', 'Radiant Grab Bag', 'Gain @NumItems@ random Radiant item(s).'),
	('656', 'Enforcer Heart', 'Your team counts as having 1 additional Enforcer. Gain a Sejuani.'),
	('824', 'TFT6_Augment_CriticalThinking_Name', 'TFT6_Augment_CriticalThinking_Description'),
	('665', 'New Recruit', 'Gain +@MaxArmySizeIncrease@ maximum team size.'),
	('602', 'Academy Heart', 'Your team counts as having 1 additional Academic. Gain a Katarina.'),
	('836', 'Mutant Crown', 'Gain 2 Mutant Emblems.'),
	('676', 'Imperial Heart', 'Your team counts as having 1 additional Imperial. Gain a Swain.'),
	('660', 'Mutant Soul', 'Your team counts as having 2 additional Mutants.'),
	('845', 'So Small', 'Yordles gain @DodgeIncrease@% Dodge Chance. Gain a Corki.'),
	('687', 'Level Up!', 'When you buy experience points, gain an additional @XP@. You can now reach level 10.'),
	('639', 'Clockwork Crest', 'Gain a Clockwork Emblem and a Zilean.'),
	('609', 'Arcanist Soul', 'Your team counts as having 2 additional Arcanists.'),
	('666', 'Golden Ticket', 'Each time your Shop is refreshed, you have a @RerollPercent@% chance to gain a free refresh.'),
	('613', 'Hexnova', 'The first time a Hextech champion drops below @HealthThreshold@% Health, they increase nearby enemies maximum Mana by @PercentManaReave@% until they cast. Gain a Nocturne.'),
	('826', 'Treasure Trove I', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('714', 'Scrap Soul', 'Your team counts as having 2 additional Scraps. Gain @Gold@ gold.'),
	('860', 'TFT6_Augment_ColossusPummel_Name', 'TFT6_Augment_ColossusPummel_Description'),
	('709', 'Scholar Soul', 'Your team counts as having 2 additional Scholars. Gain @Gold@ gold.'),
	('685', 'Makeshift Armor II', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('829', 'Treasure Trove II', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('686', 'Makeshift Armor III', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('835', 'Treasure Trove III', 'Gain @NumBlueOrbs@ blue and @NumGrayOrbs@ gray loot orb(s).'),
	('832', 'Academy Crown', 'Gain 2 Academy Emblems.'),
	('718', 'Sharpshooter', 'Twinshots ranged attacks and Abilities can bounce once, dealing @BounceReduction@% less damage. Gain a Corki.'),
	('746', 'Windfall', 'Gain gold based on the number of augments you have now.<br>0 = @Augment1Gold@g, 1 = @Augment2Gold@g, 2 = @Augment3Gold@g'),
	('684', 'Makeshift Armor I', 'Your units without items equipped gain @Resists@ Armor and Magic Resist.'),
	('800', 'Hextech Crown', 'Gain 2 Hextech Emblems.'),
	('659', 'Mutant Heart', 'Your team counts as having 1 additional Mutant. Gain a RekSai.'),
	('862', 'Battlemage III', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('626', 'Challenger Crest', 'Gain a Challenger Emblem and a Quinn.'),
	('753', 'Battlemage II', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('752', 'Battlemage I', 'Your units that start combat in the front 2 rows gain @AP@ Ability Power.'),
	('713', 'Scrap Heart', 'Your team counts as having 1 additional Scrap. Gain a Blitzcrank.'),
	('616', 'Band of Thieves', 'Gain @NumGloves@ Thiefs Gloves.'),
	('841', 'Chemtech Crown', 'Gain 2 Chemtech Emblems.'),
	('736', 'Titanic Force', 'Your units with more than @HealthThreshold@ maximum Health gain Attack Damage equal to @HealthPercent*100@% of their maximum Health.'),
	('857', 'En Garde', 'The first time an enemy is attacked by a Challenger, they are Disarmed for @DisarmDuration@ seconds. Gain a Warwick.'),
	('830', 'Imperial Crown', 'Gain 2 Imperial Emblems.'),
	('803', 'Striker Crown', 'Gain 2 Striker Emblems.'),
	('765', 'Second Wind I', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('868', 'Tiny Titans', 'Your Tactician heals @Heal@ Health, grows larger, and has @TooltipMaxHealth@ maximum Health.'),
	('767', 'Second Wind III', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('831', 'All For One', 'When an ally dies, they grant the Imperial Tyrant @MaxHealth@% of their maximum Health.'),
	('766', 'Second Wind II', 'After @Delay@ seconds of combat, your units heal @HealPercent@% of their missing Health.'),
	('754', 'Recombobulator', 'Champions on your board permanently transform into random champions that cost 1 more. Gain @NumRemovers@ Magnetic Removers.'),
	('712', 'Tinker', 'Gain a Magnetic Remover or Reforger every @Combats@ combat round(s) with the Scrap trait active.'),
	('784', 'Cybernetic Uplink II', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('785', 'Cybernetic Uplink III', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('628', 'Challenger Heart', 'Your team counts as having 1 additional Challenger. Gain a Quinn.'),
	('692', 'Gold Reserves', 'Mercenaries deal @PercentDamage*100@% more damage per @GoldIncrement@ gold you have (Maximum +@DamageCap@%). Gain a Quinn.'),
	('783', 'Cybernetic Uplink I', 'Your champions holding an item gain @Health@ Health and restore @ManaRegen@ Mana per second.'),
	('671', 'Bodyguard Soul', 'Your team counts as having 2 additional Bodyguards.'),
	('840', 'Syndicate Crest', 'Gain a Syndicate Emblem and a Zyra.'),
	('638', 'Broken Stopwatch', '@Delay@ seconds into combat, all enemies and non-Clockwork units are frozen in time for @StunDuration@ seconds. Gain a Zilean.'),
	('848', 'Sniper Crest', 'Gain a Sniper Emblem and an Ashe.'),
	('730', 'Syndicate Soul', 'Your team counts as having 2 additional Syndicates.'),
	('691', 'Mercenary Crest', 'Gain a Mercenary Emblem and @Gold@ gold.'),
	('747', 'Woodland Charm', 'At the start of combat, your highest Health Champion creates a @CloneHealth@ Health copy of themself (excluding items).'),
	('624', 'Celestial Blessing II', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('663', 'Featherweights III', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('625', 'Celestial Blessing III', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('662', 'Featherweights II', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('846', 'Featherweights I', 'Your 1 and 2 cost champions gain @AttackSpeed@% Attack Speed and Move Speed.'),
	('782', 'Meditation III', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('623', 'Celestial Blessing I', 'Your units heal for @Omnivamp@% of the damage dealt by attacks and Abilities. Excess healing is converted to a shield up to @MaxShield@ Health.'),
	('781', 'Meditation II', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('719', 'Sniper Heart', 'Your team counts as having 1 additional Sniper. Gain an Ashe.'),
	('820', 'Meditation I', 'Your units without items equipped restore @ManaRegen@ Mana per second.'),
	('798', 'Debonair Crest', 'Gain a Debonair Emblem and a Syndra.'),
	('717', 'Snipers Nest', 'Snipers gain +@DamageAmp@% damage for each round fought from the same starting hex (Maximum +@MaxAmp@%). Gain an Ashe.'),
	('672', 'High End Shopping', 'Champions appear in your Shop as if you were 1 level higher. Gain @Gold@ gold.'),
	('682', 'Component Grab Bag', 'Gain @NumComponents@ random item components.'),
	('833', 'Built Different I', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('854', 'Future Sight', 'Know who you will fight next. Gain a Zephyr.'),
	('740', 'Built Different II', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('722', 'Share the Spotlight', 'Allies adjacent to a spotlight at the start of combat gain @PercentStats@% of its bonuses. Gain a Senna.'),
	('669', 'Stand Behind Me', 'Bodyguards Armor bonus is increased by @DefenseBonus@%. At the start of combat, Bodyguards grant @DefensePercent@% of their Armor bonus to non-Bodyguard allies directly behind them (does not stack). Gain a Blitzcrank.'),
	('741', 'Built Different III', 'Your units with no Traits active gain @HP@ Health and @AS@% Attack Speed.'),
	('855', 'Woodland Trinket', 'At the start of combat, your highest Attack Speed champion creates two @CloneHealth@ Health copies of themself (excluding items).'),
	('867', 'Threes Company', 'Gain @NumChamps@ random 3-cost champions.'),
	('876', 'TFT6_Augment_NeekoNeeko_Name', 'TFT6_Augment_NeekoNeeko_Description'),
	('732', 'Wise Spending', 'Gain @Gold@ gold. When you refresh your Shop, gain @XP@ experience point(s).'),
	('673', 'Hyper Roll', 'If you have less than @ThresholdGold@ gold at the end of a round, gain @Gold@ gold.'),
	('792', 'Ludens Echo I', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('727', 'One For All', 'When your Syndicates die, they grant your other Syndicates @Stats@ Attack Damage and Ability Power. Gain an Ashe.'),
	('794', 'Ludens Echo III', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('793', 'Ludens Echo II', 'When your units cast and deal Ability damage, the first target hit and a nearby enemy take @MagicDamage@ bonus magic damage.'),
	('694', 'Mercenary Heart', 'Your team counts as having 1 additional Mercenary.'),
	('853', 'High Five', 'Gain @NumChamps@ random 5-cost champions.'),
	('837', 'Arcane Crest', 'Gain an Arcanist Emblem and a Swain.'),
	('653', 'Ardent Censer', 'Allies healed or shielded by Enchanters gain @AS@% stacking Attack Speed for the rest of combat (maximum once every @CD@ seconds). Gain a Lulu.'),
	('729', 'Syndicate Heart', 'Your team counts as having 1 additional Syndicate. Gain a Zyra.'),
	('617', 'Binary Airdrop', 'Your champions equipped with 2 items temporarily gain a random completed item at the start of combat.'),
	('615', 'Assassin Soul', 'Your team counts as having 2 additional Assassins.'),
	('667', 'High Roller', 'Gain @NumDice@ Loaded Dice and @Gold@ gold.'),
	('601', 'Academy Crest', 'Gain an Academy Emblem and a Garen.'),
	('825', 'Protector Crown', 'Gain 2 Protector Emblems.'),
	('630', 'Chemtech Crest', 'Gain a Chemtech Emblem and a Warwick.'),
	('737', 'Ancient Archives', 'Gain @NumTomes@ Tome of Traits.'),
	('631', 'Instant Injection', 'Chemtechs now additionally trigger their bonuses at the start of combat. Gain a Warwick.'),
	('771', 'Jeweled Lotus', 'Magic and true damage from your units Abilities can critically strike. Your units gain @CritChance@% Critical Strike Chance.'),
	('612', 'Assassin Crown', 'Gain 2 Assassin Emblems.'),
	('696', 'Metabolic Accelerator', 'Your Tactician moves faster and heals @Heal@ Health after a PvP round.'),
	('807', 'Disintegrator I', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('728', 'Payday', 'After winning your combat, gain @BonusGold@ bonus gold for each surviving Syndicate. Gain an Ashe.'),
	('808', 'Disintegrator II', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('632', 'Chemical Overload I', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Warwick.'),
	('809', 'Disintegrator III', 'Your units attacks deal bonus magic damage equal to @MaxHPDamage@% of the targets maximum Health.'),
	('633', 'Chemical Overload II', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Zac.'),
	('789', 'Archangels Embrace I', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('634', 'Chemical Overload III', 'Chemtechs explode on death, dealing @HP@% of their max Health as magic damage to enemies within 2 hexes. Gain a Warwick.'),
	('790', 'Archangels Embrace', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('607', 'Spell Blade', 'After casting their Ability, Arcanists next attack deals bonus magic damage equal to @PercentAbilityPower@% of their Ability Power. Gain a Swain.'),
	('791', 'Archangels Embrace III', 'Upon casting their Ability, your units gain Ability Power equal to @ManaPercent@% of their maximum Mana.'),
	('695', 'Mercenary Soul', 'Your team counts as having 2 additional Mercenaries.'),
	('839', 'Golden Gifts I', 'Gain @NumGoldOrbs@ golden and @NumGrayOrbs@ gray loot orb(s).'),
	('702', 'Protector Soul', 'Your team counts as having 2 additional Protectors.'),
	('641', 'Clockwork Soul', 'Your team counts as having 2 additional Clockworks. Gain @Gold@ gold.'),
	('866', 'The Golden Egg', 'Gain a massive golden egg that hatches in @EggTurns@ turns.'),
	('827', 'Golden Gifts II', 'Gain @NumGoldOrbs@ golden and @NumGrayOrbs@ gray loot orb(s).'),
	('745', 'Weakspot I', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('872', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('849', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('710', 'Junkyard', 'Gain a random component every @Combats@ combat rounds with the Scrap Trait active. Gain an Ezreal.'),
	('828', 'TFT6_Augment_Overclock_Name', 'TFT6_Augment_Overclock_Description'),
	('679', 'Self Repair', 'When the Innovation dies, it will become untargetable and repair itself if an Innovator is still alive. Gain a Zilean.'),
	('760', 'Thieving Rascals', 'Free Yordles from the portal have a @ItemChance@% chance to arrive holding an item component. Gain a Lulu.'),
	('708', 'Scholar Heart', 'Your team counts as having 1 additional Scholar. Gain a Zyra.'),
	('688', 'Knifes Edge I', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('635', 'Chemtech Heart', 'Your team counts as having 1 additional Chemtech. Gain a Warwick.'),
	('690', 'Knifes Edge III', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('689', 'Knifes Edge II', 'Your units that start combat in the front 2 rows gain @ADPerStarLevel@ Attack Damage.'),
	('725', 'Sunfire Board', 'At the start of combat, burn all enemies for @TotalBurnPercent@% of their maximum Health over @Duration@ seconds and reduce healing received by @GrievousWoundsPercent@%.'),
	('668', 'Bodyguard Crest', 'Gain a Bodyguard Emblem and a Darius.'),
	('661', 'Tri Force III', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('861', 'Cutthroat', 'Assassins Mana Reave the first unit they attack, increasing their maximum Mana by @ManaReavePercent@% until they cast. Gain a Talon.'),
	('851', 'Tri Force II', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('863', 'Tri Force I', 'Your 3-cost units gain @Health@ Health, @Mana@ starting Mana, and @AttackSpeed@% Attack Speed.'),
	('749', 'Backfoot I', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('750', 'Backfoot II', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('802', 'Striker Crest', 'Gain a Striker Emblem and a Reksai.'),
	('704', 'Rich Get Richer', 'Gain @Gold@ gold. Your maximum interest is increased to @InterestCap@.'),
	('751', 'Backfoot III', 'Your units that start combat in the back 2 rows gain @AS*100@% Attack Speed.'),
	('810', 'Divine Intervention', 'Gain a Radiant Blessing loot orb.'),
	('755', 'Radiant Relics', 'Open an Armory and choose 1 of @ArmoryChoiceCount@ unique Radiant items.'),
	('654', 'Enchanter Heart', 'Your team counts as having 1 additional Enchanter. Gain a Lulu.'),
	('707', 'Lifelong Learning', 'Scholars permanently gain @AP@ Ability Power after each combat, and an additional @BonusAP@ if they survived. Gain a Syndra.'),
	('619', 'Bruiser Crest', 'Gain a Bruiser Emblem and a Sejuani.'),
	('864', 'Very VIP', 'When an ally dies, they grant the Debonair VIP @MaxHealth@% of their maximum Health for the rest of combat. Gain a Syndra.'),
	('678', 'Imperial Soul', 'Your team counts as having 2 additional Imperials.'),
	('658', 'Mutant Crest', 'Gain a Mutant Emblem and a Kassadin.'),
	('834', 'Socialite Heart', 'Your team counts as having 1 additional Socialite. '),
	('756', 'Blue Battery I', 'After casting their Ability, your units restore @ManaRestore@ Mana.'),
	('674', 'Dual Rule', 'There are now @Tyrants@ Imperial Tyrants.'),
	('758', 'Blue Battery II', 'After casting their Ability, your units restore @ManaRestore@ Mana.'),
	('699', 'Portable Forge', 'Open an Armory and choose 1 of @ArmoryChoiceCount@ unique Artifacts crafted by Ornn.'),
	('838', 'Assassin Crest', 'Gain an Assassin Emblem and a Talon.'),
	('843', 'Challenger Crown', 'Gain 2 Challenger Emblems.'),
	('711', 'Scrap Crest', 'Gain a Scrap Emblem and a Blitzcrank.'),
	('847', 'Bodyguard Crown', 'Gain 2 Bodyguard Emblems.'),
	('681', 'Innovator Soul', 'Your team counts as having 2 additional Innovators.'),
	('622', 'Calculated Loss', 'After losing your combat, gain @Gold@ gold and a free Shop refresh.'),
	('842', 'Bruiser Crown', 'Gain 2 Bruiser Emblems.'),
	('621', 'Bruiser Soul', 'Your team counts as having 2 additional Bruisers.'),
	('700', 'Protector Crest', 'Gain a Protector Emblem and a Garen.'),
	('664', 'First Aid Kit', 'All healing and shielding on your units is increased by @HealShieldIncrease*100@%.'),
	('762', 'Electrocharge I', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('768', 'Arcane Nullifier I', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('636', 'Chemtech Soul', 'Your team counts as having 2 additional Chemtechs.'),
	('764', 'Electrocharge III', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('770', 'Arcane Nullifier III', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('763', 'Electrocharge II', 'When your units receive critical strikes, they deal @Damage@ magic damage to nearby enemies. (@ICD@ second cooldown).'),
	('769', 'Arcane Nullifier II', 'Your units Abilities ignore @MagicPen@% of the targets Magic Resist and reduce healing received by @HealingReduction@% for @Duration@ seconds.'),
	('742', 'Twinshot Heart', 'Your team counts as having 1 additional Twinshot. Gain a Corki.'),
	('655', 'Enchanter Soul', 'Your team counts as having 2 additional Enchanters. Gain @Gold@ gold.'),
	('865', 'Stored Power', 'Your Hextech champions permanently gain @AP@ Ability Power each time they are hit by your Hexcores pulses. Gain a Swain.'),
	('869', 'Double Trouble II', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('852', 'Phalanx III', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('870', 'Double Trouble III', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('780', 'Phalanx II', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('779', 'Phalanx I', 'Your units that start combat in the back 2 rows gain @Resists@ Armor and Magic Resist.'),
	('645', 'Cybernetic Implants III', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('739', 'Double Trouble I', 'If you have exactly 2 copies of a champion on your board, they both gain @BonusStats@ Attack Damage, Ability Power, Armor, and Magic Resist. When you 3-star, gain a 2-star copy.'),
	('744', 'Underdogs', 'Whenever your team has fewer units alive than your opponent, your units regenerate @MissingHeal@% Health each second (maximum: @HealCap@).'),
	('644', 'Cybernetic Implants II', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('643', 'Cybernetic Implants I', 'Your champions holding an item gain @HP@ Health and @AD@ Attack Damage.'),
	('806', 'Weakspot III', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('805', 'Weakspot II', 'Your units attacks ignore @ArmorPenPercent@% of the targets Armor and reduce healing received by @HealReductionPercent@% for @Duration@ seconds.'),
	('652', 'Dominance', 'After winning your player combat, gain @Gold@ bonus gold for every @PerSurvivingUnit@ surviving units.'),
	('646', 'Exiles', 'Your units that start combat with no adjacent allies gain a @MaxHealthShield@% maximum Health shield for @ShieldDuration@ seconds.'),
	('697', 'Unstable Evolution', 'Mutants randomly gain one of the following when they reach 2 star: @BonusHP@ Health, @BonusAS@% Attack Speed, @BonusAD@ Attack Damage, or @BonusAP@ Ability Power. These bonuses stack. Gain a RekSai.'),
	('618', 'Shrug It Off', 'Bruisers regenerate @RegenPerTick@% of their maximum Health each second. Gain a Sejuani.'),
	('640', 'Clockwork Heart', 'Your team counts as having 1 additional Clockwork. Gain a Zilean.'),
	('812', 'Keepers II', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('720', 'Sniper Soul', 'Your team counts as having 2 additional Snipers.'),
	('813', 'Keepers III', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('738', 'Trade Sector', 'Gain a free Shop refresh each round.'),
	('811', 'Keepers I', 'At the start of combat, your units grant adjacent allies a @ShieldHealth@ health shield for @ShieldDuration@ seconds.'),
	('844', 'Arcanist Crown', 'Gain 2 Arcanist Emblems.'),
	('721', 'Duet', 'Summon 1 additional Socialite spotlight. Spotlighted units gain @BonusHealth@ Health. Gain a Senna.'),
	('627', 'Concussive Blows', 'Strikers critical strikes stun their target for @StunDuration@ second(s). Each target can only be stunned once every @StunCD@ seconds. Gain a RekSai.'),
	('705', 'Salvage Bin', 'Gain a random completed item. Selling champions breaks apart their full items into components (excluding Tacticians Crown).'),
	('822', 'Chemtech Unity', 'The Chemtech trait grants its bonuses to all of your Champions. This does not increase your number of Chemtech units. Gain a Warwick.'),
	('620', 'Bruiser Heart', 'Your team counts as having 1 additional Bruiser. Gain a Sejuani.'),
	('670', 'Bodyguard Heart', 'Your team counts as having 1 additional Bodyguard. Gain a Blitzcrank.'),
	('629', 'Challenger Soul', 'Your team counts as having 2 additional Challengers.'),
	('799', 'Hextech Crest', 'Gain a Hextech Emblem and a Nocturne.'),
	('850', 'Future Sight II', 'Know who you will fight next. Gain a Radiant Zephyr.'),
	('788', 'Cybernetic Shell III', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('787', 'Cybernetic Shell II', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('786', 'Cybernetic Shell I', 'Your champions holding an item gain @Health@ Health and @Resists@ Armor.'),
	('873', 'TFT6_Augment_InfinityCane_Name', 'TFT6_Augment_InfinityCane_Description'),
	('608', 'Arcanist Heart', 'Your team counts as having 1 additional Arcanist. Gain a Swain.'),
	('637', 'Clear Mind', 'If you have no champions on your bench at the end of a round, gain @XP@ experience points.'),
	('675', 'Imperial Crest', 'Gain an Imperial Emblem and a Swain.'),
	('483', 'tft_item_name_Mercenary_Book', 'tft_item_description_Mercenary_Dice'),
	('432', 'tft_item_name_Mercenary_Bag', 'tft_item_description_Mercenary_Dice'),
	('492', 'tft_item_name_Mercenary_Spatula', 'tft_item_description_Mercenary_Dice'),
	('436', 'tft_item_name_Mercenary_Fish', 'tft_item_description_Mercenary_Dice'),
	('490', 'tft_item_name_Mercenary_Chest', 'tft_item_description_Mercenary_Dice'),
	('491', 'tft_item_name_Mercenary_Sword', 'tft_item_description_Mercenary_Dice'),
	('485', 'tft_item_name_Mercenary_X', 'tft_item_description_Mercenary_Dice'),
	('411', 'tft_item_name_Mercenary_Shell', 'tft_item_description_Mercenary_Dice'),
	('486', 'tft_item_name_Mercenary_Kraken', 'tft_item_description_Mercenary_Dice'),
	('403', 'tft_item_name_Mercenary_X', 'tft_item_description_Mercenary_Dice'),
	('487', 'tft_item_name_Mercenary_Ship', 'tft_item_description_Mercenary_Dice'),
	('484', 'tft_item_name_Mercenary_Coin', 'tft_item_description_Mercenary_Dice'),
	('488', 'tft_item_name_Mercenary_Soldier', 'tft_item_description_Mercenary_Dice'),
	('463', 'Small Prize', '1 gold has been added to your chest.'),
	('474', 'Large Prize', '50 gold has been added to your chest.'),
	('443', 'Golden Chest', 'Gain a Thiefs Gloves. '),
	('451', 'Small Prize', '6 gold has been added to your chest.'),
	('473', 'Golden Book', 'Gain a Tome of Traits.'),
	('450', 'Large Prize', '3 4-cost champions are placed in your chest.'),
	('429', 'Golden Sword', 'Gain 1 5-cost champion and 2 gold.'),
	('444', 'Small Prize', '5 gold has been added to your chest.'),
	('421', 'Large Prize', '1 Chalice of Power, 1 Zekes Herald, and 10 gold are placed in your chest.'),
	('482', 'Large Prize', '1 Spatula has been added to your chest.'),
	('437', 'Small Prize', '6 gold has been added to your chest.'),
	('428', 'Large Prize', 'A Loaded Dice and 2 gold are placed in your chest.'),
	('449', 'Small Prize', '4 gold has been added to your chest.'),
	('445', 'Large Prize', '1 Loaded Dice has been added to your chest. '),
	('452', 'Large Prize', 'A defensive component and 2 gold has been added to your chest.'),
	('409', 'Golden Bag', 'Gain 1 item.'),
	('413', 'Golden Soldier', 'Gain 2 5-cost champions.'),
	('447', 'JACKPOT', 'A Thiefs Gloves has been added to your chest.'),
	('424', 'JACKPOT', '2 5-cost champions are placed in your chest.'),
	('467', 'Large Prize', '1 utility component and 1 Neekos Help has been added to your chest.'),
	('434', 'Large Prize', '1 defensive component and 1 Neekos Help has been added to your chest.'),
	('441', 'JACKPOT', '8 gold has been added to your chest.'),
	('446', 'Small Prize', 'A 4-cost champion has been added to your chest. '),
	('419', 'Large Prize', '3 3-cost champions are placed in your chest. '),
	('418', 'Large Prize', 'A 4-cost champion and 3 gold has been added to your chest.'),
	('414', 'Large Prize', '1 Dragons Claw, 1 Bramblevest, and 10 gold are placed in your chest.'),
	('442', 'JACKPOT', 'A 2-star 5-cost has been added to your chest.'),
	('459', 'JACKPOT', '4 gold has been added to your chest.'),
	('457', 'Golden Ship', 'Gain 3 item components.'),
	('438', 'Large Prize', '1 Neekos Help has been added to your chest.'),
	('469', 'Large Prize', '1 offensive component and 1 Neekos Help has been added to your chest.'),
	('448', 'Small Prize', '10 gold has been added to your chest.'),
	('479', 'JACKPOT', '2 Loaded Dice and a 2-star 4-cost are placed in your chest.'),
	('410', 'Small Prize', '6 gold has been added to your chest.'),
	('462', 'No Prize', 'Yarr!!! You got nothing. Try again next round. '),
	('407', 'Large Prize', '1 Neekos Help and 2 gold has been added to your chest.'),
	('408', 'Small Prize', '2 2-cost champions are placed in your chest. '),
	('477', 'Large Prize', '25 gold has been added to your chest.'),
	('468', 'Small Prize', '10 gold has been added to your chest.'),
	('440', 'JACKPOT', '1 item component and 1 Neekos Help has been added to your chest.'),
	('455', 'Large Prize', '2 4-cost champions are placed in your chest.'),
	('431', 'Golden Kraken', 'Gain 1 Neekos Help and 3 gold.'),
	('476', 'Large Prize', '10 gold has been added to your chest.'),
	('470', 'Large Prize', '1 offensive item component has been added to your chest. '),
	('412', 'Small Prize', '3 gold has been added to your chest.'),
	('475', 'JACKPOT', 'A Tome of Traits has been added to your chest.'),
	('465', 'Large Prize', 'A utility item component has been added to your chest.'),
	('417', 'Large Prize', '1 Neekos Help and 5 gold has been added to your chest.'),
	('423', 'Small Prize', '4 gold has been added to your chest.'),
	('481', 'Large Prize', 'A 5-cost champion and 10 gold has been added to your chest.'),
	('420', 'Small Prize', '2 gold has been added to your chest.'),
	('427', 'Large Prize', 'A 4-cost champion and 10 gold has been added to your chest.'),
	('460', 'JACKPOT', '1 item component has been added to your chest.'),
	('472', 'JACKPOT', '2 Thiefs Gloves and 10 gold are placed in your chest.'),
	('461', 'Large Prize', '1 random full item and 2 components are placed in your chest.'),
	('480', 'JACKPOT', 'A Tacticians Crown has been added to your chest.'),
	('422', 'JACKPOT', 'A Spatula has been added to your chest.'),
	('425', 'Large Prize', 'An offensive component and 2 gold has been added to your chest.'),
	('466', 'Large Prize', 'A defensive item component has been added to your chest.'),
	('426', 'Small Prize', '7 gold has been added to your chest.'),
	('406', 'Small Prize', '8 gold has been added to your chest.'),
	('464', 'Small Prize', '3 gold has been added to your chest.'),
	('458', 'JACKPOT', '2 4-cost champions are placed in your chest.'),
	('416', 'JACKPOT', '2 item components are placed in your chest.'),
	('478', 'JACKPOT', '1 full item and 2 Neekos Help have been added to your chest.'),
	('454', 'Large Prize', '2 4-cost champions are placed in your chest.'),
	('415', 'Large Prize', 'A 4-cost champion and 10 gold has been added to your chest.'),
	('439', 'Large Prize', 'A utility component and 2 gold has been added to your chest.'),
	('471', 'Large Prize', '2 3-cost champions are placed in your chest.'),
	('456', 'Golden Spatula', 'Gain a Tacticians Crown'),
	('453', 'Small Prize', 'A 3-cost champion has been added to your chest.'),
	('433', 'Golden Shell', 'Gain 3 Frozen Hearts.'),
	('33', 'Rabadons Deathcap', 'Grants %i:scaleAP% @AP@ bonus Ability Power (including components).'),
	('19', 'Infinity Edge', 'Grants @CritChance@% Critical Strike Chance (including components) and @BonusCritDamage@% Critical Strike Damage. Each point of Critical Strike Chance above 100% becomes +@BonusCritDmgPerCritAbove100@% Critical Strike Damage. <br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2066', 'Dragons Will', 'Grants %i:scaleMR% <TFTRadiantItemBonus>@MagicResist@</TFTRadiantItemBonus> bonus Magic Resist (including components). On being hit by magic or true damage from an Ability, launch a fireball at the Abilitys caster that deals magic damage equal to <TFTRadiantItemBonus>@PercentHealthDamage@% of their max Health</TFTRadiantItemBonus> (@ICD@ second cooldown).<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus>'),
	('2079', 'Banshees Silence', 'When combat begins, the holder <TFTRadiantItemBonus>and all allies</TFTRadiantItemBonus> gain a shield that blocks the damage and effects of the first enemy Ability, up to 600 damage. <br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusAllyHealth@ Health for all allies</TFTRadiantItemBonus> at the start of combat.'),
	('2036', 'Covalent Spark', 'Enemies within <TFTRadiantItemBonus>@HexRange@</TFTRadiantItemBonus> hexes have their Magic Resist reduced by @MRShred@%. When they cast an Ability, they are zapped taking magic damage equal to <TFTRadiantItemBonus>@ManaRatio@%</TFTRadiantItemBonus> of their max Mana.<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus><br>'),
	('2069', 'Quickestsilver', 'The holder gains %i:scaleAS% <TFTRadiantItemBonus>@AS@%</TFTRadiantItemBonus> bonus Attack Speed.  The holder is immune to crowd control in combat for <TFTRadiantItemBonus>@SpellShieldDuration@</TFTRadiantItemBonus> seconds. <br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2013', 'Hextech Lifeblade', 'The holders magic and true damage from Abilities heal them for <TFTRadiantItemBonus>@OmniVamp@%</TFTRadiantItemBonus> of the damage dealt. <TFTRadiantItemBonus>Excess healing fuels a shield that protects the holder against up to @ShieldMax@ damage.</TFTRadiantItemBonus> The holder also heals their lowest health ally for the same amount.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusAP@ Ability Power.</TFTRadiantItemBonus>'),
	('2024', 'Statikks Favor', 'The holder gains %i:scaleAS% @BonusAS@% bonus Attack Speed. Every 3rd attack from the holder unleashes a chain lightning that bounces to <TFTRadiantItemBonus>@1StarBounces@</TFTRadiantItemBonus> enemies, dealing <TFTRadiantItemBonus>@Damage@</TFTRadiantItemBonus> magic damage and reducing their Magic Resist by @MRShred@% for @MRShredDuration@ seconds.'),
	('2045', 'Frozen Heart Of Gold', 'Reduces the Attack Speed of enemies within @HexRadius@ hexes by <TFTRadiantItemBonus>@AttackSpeedSlow@%</TFTRadiantItemBonus>.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusMana@ Starting Mana.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2044', 'Blue Blessing', 'The holder gains %i:scaleMana% @Mana@ Starting Mana (including components). After casting their Ability, the holder gains %i:scaleMana% <TFTRadiantItemBonus>@ManaRestore@</TFTRadiantItemBonus> mana.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@AP@ Ability Power. </TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2034', 'Urf-Angels Staff', 'During combat, the holder gains %i:scaleAP% <TFTRadiantItemBonus>@APPerInterval@</TFTRadiantItemBonus> Ability Power every <TFTRadiantItemBonus>@IntervalSeconds@</TFTRadiantItemBonus> seconds.'),
	('2037', 'More More-ellonomicon', 'When the holder deals magic or true damage with their Ability, they burn the target, dealing <TFTRadiantItemBonus>@BurnPercent@%</TFTRadiantItemBonus> of the targets maximum Health as true damage over <TFTRadiantItemBonus>@BurnDuration@</TFTRadiantItemBonus> seconds, and reducing healing by @GrievousWoundsPercent@% for the duration of the burn.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@Mana@ Starting Mana.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2055', 'Rosethorn Vest', 'Grants %i:scaleArmor% @Armor@ bonus Armor (including components). Negates bonus damage from incoming critical strikes. On being hit by an attack, deal <TFTRadiantItemBonus>@1StarAoEDamage@/@2StarAoEDamage@/@3StarAoEDamage@</TFTRadiantItemBonus> %i:star% magic damage to all nearby enemies (once every @ICD@ seconds).<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus>'),
	('2027', 'ZzRots Invitation', '<TFTRadiantItemBonus>At the start of combat, a Radiant Voidmother with bonus Health and Attack Damage</TFTRadiantItemBonus> arises and taunts enemies within <TFTRadiantItemBonus>@HexRadius@</TFTRadiantItemBonus> hexes. Radiant Voidmothers that arise from summoned units are @SummonedStatReduction@% effective.'),
	('2059', 'Shroud of Reverence', 'When combat begins, the holder shoots a <TFTRadiantItemBonus>wider beam</TFTRadiantItemBonus> straight ahead that delays affected enemies first spellcast, increasing their max Mana by <TFTRadiantItemBonus>@CostIncrease@%</TFTRadiantItemBonus> until they cast.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@AllyBonusMana@ Starting Mana for all allies</TFTRadiantItemBonus> at the start of combat.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2026', 'Runaans Tempest', 'The holder gains %i:scaleAD% @AD@ Attack Damage. The holders attacks fire a bolt at another nearby enemy, dealing <TFTRadiantItemBonus>@MultiplierForDamage@%</TFTRadiantItemBonus> of the holders Attack Damage as physical damage.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusAS@% Attack Speed.</TFTRadiantItemBonus>'),
	('2067', 'Mistral', 'When combat begins, the holder summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for <TFTRadiantItemBonus>@BanishDuration@</TFTRadiantItemBonus> seconds. Ignores crowd control immunity.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@AllyBonusAS@% Attack Speed for all allies</TFTRadiantItemBonus> at the start of combat.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2023', 'Guinsoos Reckoning', 'Attacks grant <TFTRadiantItemBonus>+@AttackSpeedPerStack@%</TFTRadiantItemBonus> bonus Attack Speed for the rest of combat.<br><br>This effect can stack any number of times.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@RadiantBonusAS@% Attack Speed.</TFTRadiantItemBonus>'),
	('2049', 'Fist of Fairness', 'At the beginning of each planning phase, the holder gains <TFTRadiantItemBonus>both of the following</TFTRadiantItemBonus>:<li>+@BonusAD@ Attack Damage and +@BonusSP@ Ability Power.</li> <li>Attacks and Abilities heal for @TraitMultiplier@% of damage dealt.</li>'),
	('2057', 'Sunlight Cape', 'Every <TFTRadiantItemBonus>@ICD@</TFTRadiantItemBonus> seconds, a random enemy within <TFTRadiantItemBonus>@HexRange@</TFTRadiantItemBonus> hexes is burned for <TFTRadiantItemBonus>@BurnPercent@% of their maximum Health as true damage over @BurnDuration@ seconds</TFTRadiantItemBonus>. Any healing they receive is reduced by @GrievousWoundsPercent@%.<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2017', 'Zekes Harmony', 'When combat begins, the holder and all allies within @HexRange@ hexes in the same row gain %i:scaleAS% <TFTRadiantItemBonus>@AttackSpeed@%</TFTRadiantItemBonus> Attack Speed <TFTRadiantItemBonus>and @Lifesteal@% Lifesteal</TFTRadiantItemBonus> for the rest of combat.'),
	('2029', 'Eternal Whisper', 'When the holder inflicts a critical hit, the targets Armor is reduced by @ArmorReductionPercent@% for <TFTRadiantItemBonus>the rest of combat.</TFTRadiantItemBonus> This effect does not stack.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusCritChance@% Critical Strike Chance.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('2035', 'Locket of Targon Prime', 'When combat begins, the holder and all allies within <TFTRadiantItemBonus>@HexRange@</TFTRadiantItemBonus> hexes in the same row gain a shield that blocks <TFTRadiantItemBonus>@1StarShieldValue@/@2StarShieldValue@/@3StarShieldValue@</TFTRadiantItemBonus> %i:star% damage for <TFTRadiantItemBonus>@ShieldDuration@</TFTRadiantItemBonus> seconds.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusAllyHealth@ Health for all allies</TFTRadiantItemBonus> at the start of combat.'),
	('2099', 'Rascals Gloves', 'At the beginning of each planning phase, the holder equips 2 temporary <TFTRadiantItemBonus>Radiant items.</TFTRadiantItemBonus><br><br><tftitemrules>[Consumes Three Item Slots]</tftitemrules>'),
	('2077', 'Warmogs Pride', 'Grants %i:scaleHealth% <TFTRadiantItemBonus>@Health@</TFTRadiantItemBonus> bonus Health (including components).<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus>'),
	('2047', 'Radiant Redemption', 'Every @HealTickRate@ seconds, the holder radiates an aura to allies within <TFTRadiantItemBonus>@HexRadius@</TFTRadiantItemBonus> hexes, healing them for <TFTRadiantItemBonus>@MissingHealthHeal@%</TFTRadiantItemBonus> of their missing Health. Affected allies take @AoEDamageReduction@% reduced damage from multi-target abilities and attacks for @HealTickRate@ seconds.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusHealth@ Health.</TFTRadiantItemBonus>'),
	('2015', 'Brink of Dawn', 'When the holder first drops below @HealthThreshold@% Health, they briefly enter stealth, becoming untargetable and shedding negative effects. After coming out of stealth, the holder gains an additional <TFTRadiantItemBonus>%i:scaleAS% @AttackSpeed@%</TFTRadiantItemBonus> bonus Attack Speed.<br><br><TFTRadiantItemBonus>Radiant Bonus: Triggers again at @HealthThreshold2@% Health.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2022', 'Rapid Lightcannon', 'Increases the holders Attack Range by <TFTRadiantItemBonus>@HexRangeIncrease@</TFTRadiantItemBonus> hexes and grants %i:scaleAS% @AS@% bonus Attack Speed (including components). The holders attacks can no longer miss.'),
	('2025', 'Titans Vow', 'When the holder attacks or takes damage, they gain <TFTRadiantItemBonus>@StackingAD@ Attack Damage and Ability Power</TFTRadiantItemBonus>.<br><br>This stacks up to @StackCap@ times, at which point the holder gains <TFTRadiantItemBonus>@BonusResistsAtStackCap@ Armor and Magic Resist</TFTRadiantItemBonus>.'),
	('2012', 'Demonslayer', 'The holders Abilities and attacks do <TFTRadiantItemBonus>@SmallBonusPct@%</TFTRadiantItemBonus> bonus damage. If the target has more than <TFTRadiantItemBonus>@HealthThreshold@ maximum Health</TFTRadiantItemBonus>, the bonus increases to <TFTRadiantItemBonus>@LargeBonusPct@%</TFTRadiantItemBonus>.'),
	('2016', 'Blessed Bloodthirster', 'Physical damage heals the holder for <TFTRadiantItemBonus>@Lifesteal@%</TFTRadiantItemBonus> of the damage dealt. Upon falling below @HealthThreshold@% Health, the holder gains a <TFTRadiantItemBonus>@ShieldHealthPercent@%</TFTRadiantItemBonus> max Health shield that lasts up to @ShieldDuration@ seconds.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@BonusAD@ Attack Damage.</TFTRadiantItemBonus>'),
	('2033', 'Rabadons Ascended Deathcap', 'Grants %i:scaleAP% <TFTRadiantItemBonus>@AP@</TFTRadiantItemBonus> bonus Ability Power (including components).'),
	('2039', 'Glamorous Gauntlet', 'The holders magic and true damage from their Ability can critically strike. The holder gains <TFTRadiantItemBonus>@CritDamageAmp@%</TFTRadiantItemBonus> bonus Critical Strike Damage and %i:scaleAP% @TooltipBonusAP@ bonus Ability Power.'),
	('2056', 'Dvarapala Stoneplate', 'The holder gains %i:scaleArmor% <TFTRadiantItemBonus>@ArmorPerEnemy@</TFTRadiantItemBonus> Armor and %i:scaleMR% <TFTRadiantItemBonus>@MRPerEnemy@</TFTRadiantItemBonus> Magic Resist for each enemy targeting them.<br><br><TFTRadiantItemBonus>Radiant Bonus: Regenerate @MaxHealthRegen@% max Health per second.</TFTRadiantItemBonus>'),
	('2046', 'Chalice of Charity', 'When combat begins, the holder and all allies within @HexRange@ hex in the same row gain %i:scaleAP% <TFTRadiantItemBonus>@BonusAP@</TFTRadiantItemBonus> Ability Power for the rest of combat. <TFTRadiantItemBonus>Additionally, magic and true damage from their Abilities heal them for @Spellvamp@% of the damage dealt.</TFTRadiantItemBonus>'),
	('2014', 'Spear of Hirana', 'The holders attacks restore %i:scaleMana% <TFTRadiantItemBonus>@FlatManaRestore@</TFTRadiantItemBonus> additional Mana.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@AP@ Ability Power. </TFTRadiantItemBonus>'),
	('2019', 'Zenith Edge', 'Grants @CritChance@% Critical Strike Chance (including components) and @BonusCritDamage@% Critical Strike Damage. Each point of Critical Strike Chance above 100% becomes +@BonusCritDmgPerCritAbove100@% Critical Strike Damage.<br><br><TFTRadiantItemBonus>Radiant Bonus: +@RadiantBonusCritDamage@% Critical Strike Damage.</TFTRadiantItemBonus><br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2011', 'Luminous Deathblade', 'The holder gains %i:scaleAD% <TFTRadiantItemBonus>@Tooltip1StarBonusAD@/@Tooltip2StarBonusAD@/@Tooltip3StarBonusAD@</TFTRadiantItemBonus> %i:star% bonus Attack Damage (including components).'),
	('45', 'Frozen Heart', 'Reduces the Attack Speed of enemies within @HexRadius@ hexes by @AttackSpeedSlow@%.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2194', 'Enforcer Emblem', 'The holder gains the Enforcer trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('210', 'Kayns Liberation', 'Place on Kayn to free him from Rhaast, permanently improving his Reaping Slash spell to deal bonus damage at the start of combat.<br><br><tftitemrules>[KAYN CONSUMABLE - This item disappears when used and DESTROYS Rhaasts Embrace]</tftitemrules><br><br><tftitemrules>[Can only be used during the Planning Phase]</tftitemrules>'),
	('-46', 'tft_item_name_Hush', 'TFT_item_description_Hush'),
	('59', 'Shroud of Stillness', 'When combat begins, the holder shoots a beam straight ahead that delays affected enemies first cast, increasing their max Mana by @CostIncrease@% until they cast.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('206', 'Shadow Transformer', 'Turns all items on a champion into shadow items when used.<br><br><tftitemrules>[CONSUMABLE - This item disappears when used.]</tftitemrules><br><tftitemrules>This Item cannot transform Force of Nature, which is above corruption.</tftitemrules>'),
	('47', 'Redemption', 'Every @HealTickRate@ seconds, the holder radiates an aura to allies within @HexRadius@ hex, healing them for @MissingHealthHeal@% of their missing Health. Affected allies take @AoEDamageReduction@% reduced damage from multi-target abilities and attacks for @HealTickRate@ seconds.'),
	('67', 'Zephyr', 'When combat begins, the holder summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for @BanishDuration@ seconds. Ignores crowd control immunity.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('10203', 'tft_item_name_OceanHexBuff', 'tft_item_description_OceanHexBuff'),
	('2191', 'Clockwork Emblem', 'The holder gains the Clockwork trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('9005', 'Manazane', 'After the wearer casts their spell for the first time each combat, they restore %i:scaleMana% @ManaRestore@ Mana over @ManaDuration@ seconds.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('202', 'Reforger', 'Use on a champion to unequip all items and randomly transform them into different new ones. <br><br><tftitemrules> [SAME QUALITY: Reforging an item will grant a new item of a similar type and quality.<br> Cannot be used on board champions in combat, or on Tacticians Crown.<br> CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('-28', 'TFT_item_name_BladeOfTheRuinedKing', 'TFT_item_description_BladeOfTheRuinedKing'),
	('17', 'Zekes Herald', 'When combat begins, the holder and all allies within @HexRange@ hexes in the same row gain %i:scaleAS% @AttackSpeed@% Attack Speed for the rest of combat.'),
	('99', 'Thiefs Gloves', 'At the beginning of each planning phase, the holder equips 2 temporary items. Temporary items increase in power based on your player level.<br><br><tftitemrules>[Consumes 3 item slots.]</tftitemrules>'),
	('2203', 'One 3+ Cost Unit', 'One 3+ Cost Unit'),
	('23', 'Guinsoos Rageblade', 'Attacks grant +@AttackSpeedPerStack@% bonus Attack Speed for the rest of combat. This effect can stack any number of times.'),
	('36', 'Ionic Spark', 'Enemies within @HexRange@ hexes have their Magic Resist reduced by @MRShred@%. When they cast an Ability, they are zapped taking magic damage equal to @ManaRatio@% of their maximum Mana.'),
	('66', 'Dragons Claw', 'Grants %i:scaleMR% @MagicResist@ bonus Magic Resist (including components). On being hit by magic or true damage from a casted Ability, launch a fireball at the Abilitys caster that deals magic damage equal to @PercentHealthDamage@% of their maximum Health (@ICD@ second cooldown).'),
	('203', 'Magnetic Remover', 'Use on a champion to unequip all items. <br><br><tftitemrules> [Cannot be used on board champions in combat.]<br>[CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('-25', 'TFT_item_name_PhantomDancer', 'TFT_item_description_PhantomDancer'),
	('79', 'Banshees Claw', 'When combat begins, the holder and all allies within @HexRange@ hex(es) in the same row gain a shield that blocks the damage and effects of the first enemy Ability, up to 600 damage. <br>'),
	('2192', 'Mercenary Emblem', 'The holder gains the Mercenary trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('2201', 'Two 1-Cost & One 2-Cost Units', 'Two 1-Cost & One 2-Cost Units'),
	('10006', 'Loot Bag', 'Loot goes here'),
	('209', 'Light Transformer', 'Turns all items on a champion into standard items when used.<br><br><tftitemrules>[CONSUMABLE - This item disappears when used.]</tftitemrules><br><tftitemrules>This Item cannot transform Force of Darkness, which is beyond redemption.</tftitemrules>'),
	('208', 'Rhaasts Embrace', 'Place on Kayn to force Rhaast to overtake him, permanently improving his Reaping Slash spell to heal him.<br><br><tftitemrules>[KAYN CONSUMABLE - This item disappears when used and DESTROYS Kayns Liberation]</tftitemrules><br><br><tftitemrules>[Can only be used during the Planning Phase]</tftitemrules>'),
	('58', 'Bodyguard Emblem', 'The holder gains the Bodyguard trait.<br><br><tftitemrules>[Unique - only 1 per champion <br>Elusive - cannot be crafted.]</tftitemrules>'),
	('200', 'Neekos Help', 'Place on a champion to create a one-star copy of them.<br><br><tftitemrules>[CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('61', 'Blue Buff', 'The holder gains %i:scaleMana% @Mana@ Starting Mana (including components). After casting their Ability, the holder gains %i:scaleMana% @ManaRestore@ mana.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('-5', 'Chain Vest', '%i:scaleArmor% +@Armor@ Armor'),
	('-2', 'B.F. Sword', '%i:scaleAD% +@AD@ Attack Damage'),
	('15', 'Guardian Angel', 'Prevents the holders first death, placing them in stasis instead. After @StasisDuration@ seconds, they return with @HealthRestore@ Health and shed all negative effects.<br><br><tftitemrules>[Unique - Only One Per Champion]</tftitemrules>'),
	('-55', 'game_item_displayname_3075', 'tft_item_description_Thornmail'),
	('305', 'tft_item_name_EmblemArmoryConsumable', 'tft_item_description_EmblemArmoryConsumable'),
	('2213', '8 Gold', '8 Gold'),
	('9001', 'Anima Visage', 'The wearer regenerates @PercentHealthRegen@% of their maximum Health each second.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('56', 'Gargoyle Stoneplate', 'The holder gains %i:scaleArmor% @ArmorPerEnemy@ Armor and %i:scaleMR% @MRPerEnemy@ Magic Resist for each enemy targeting them.'),
	('55', 'Bramble Vest', 'Grants %i:scaleArmor% @Armor@ bonus Armor (including components). Negates @CritReduction@% bonus damage from incoming critical strikes. On being hit by an attack, deal @1StarAoEDamage@/@2StarAoEDamage@/@3StarAoEDamage@ %i:star% magic damage to all nearby enemies (once every @ICD@ seconds).'),
	('5', 'Chain Vest', '%i:scaleArmor% +@Armor@ Armor'),
	('9008', 'Rocket-Propelled Fist', 'At the start of combat, the holder pulls the farthest enemy into melee range, stunning them for @StunDuration@ seconds. Allies within range will prioritize attacking that enemy.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('-59', 'tft_item_name_FrozenFist', 'tft_item_description_FrozenFist'),
	('529', 'tft_item_name_SpellThiefsEdge', 'tft_item_description_SpellThiefsEdge'),
	('2210', '5 Gold', '5 Gold'),
	('2211', '6 Gold', '6 Gold'),
	('2212', '7 Gold', '7 Gold'),
	('9003', 'Eternal Winter', 'Enemies who damage the holder have their Attack Speed slowed by @AttackSpeedSlowPercent@% for @SlowDuration@ seconds. After being slowed this way @NumApplications@ times, the attacker is Frozen for the duration instead. An enemy can only be Frozen once every @FreezeCooldown@ seconds.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2196', 'Protector Emblem', 'The holder gains the Protector trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('2198', 'Innovator Emblem', 'The holder gains the Innovator trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('149', 'TFT_item_name_Catalyst', 'TFT_item_description_Catalyst'),
	('10204', 'tft_item_name_WindHexBuff', 'tft_item_description_WindHexBuff'),
	('2200', 'Scholar Emblem', 'The holder gains the Scholar trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('2', 'Recurve Bow', '%i:scaleAS% +@AS@ Attack Speed'),
	('12', 'Giant Slayer', 'The holders Abilities and attacks do @SmallBonusPct@% bonus damage. If the target has more than @HealthThreshold@ maximum Health, the bonus increases to @LargeBonusPct@%.'),
	('10201', 'tft_item_name_InfernoHexBuff', 'tft_item_description_InfernoHex'),
	('9006', 'Obsidian Cleaver', 'The wearers attacks and spell damage shred enemy Armor and Magic Resistance by @Shred@% for @Duration@ seconds.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('57', 'Sunfire Cape', 'Every @ICD@ seconds, a random enemy within @HexRange@ hexes is burned for @BurnPercent@% of their maximum Health as true damage over @BurnDuration@ seconds. Any healing they receive is reduced by @GrievousWoundsPercent@%.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2220', 'Random Component', 'Random Component'),
	('2204', 'Two 3+Cost Units', 'Two 3+Cost Units'),
	('18', 'Imperial Emblem', 'The holder gains the Imperial trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('205', 'Divine Dissolver', 'Use on a champion to break apart all items into components and unequip them.<br><br><tftitemrules> [Cannot be used on board champions in combat.]<br>[CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('-100', 'tft_item_name_SwordOfTheDivine2', 'tft_item_description_SwordOfTheDivine2'),
	('49', 'Hand Of Justice', 'The holder gains both of the following:<li>+@BaseAD@ Attack Damage and +@BaseSP@ Ability Power.</li> <li>Attacks and Abilities heal for @BaseHeal@% of damage dealt.</li><br><br>At the beginning of each planning phase, one of these buffs is increased to @TooltipBonus@(%).<br>'),
	('-26', 'tft_item_name_CursedBlade', 'TFT_item_description_CursedBlade'),
	('94', 'Edge of Night', 'When the holder first drops below @HealthThreshold@% health, they briefly enter stealth, becoming untargetable and shedding negative effects. After coming out of stealth, the holder gains an additional %i:scaleAS% @AttackSpeed@% bonus Attack Speed.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('44', 'Blue Buff', 'The holder gains %i:scaleMana% @Mana@ Starting Mana (including components). After casting their Ability, the holder gains %i:scaleMana% @ManaRestore@ mana.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('4', 'Tear of the Goddess', '%i:scaleMana% +@Mana@ Mana'),
	('10004', 'Deathblade', 'The holder gains %i:scaleAD% @Tooltip1StarBonusAD@/@Tooltip2StarBonusAD@/@Tooltip3StarBonusAD@ %i:star% bonus Attack Damage (including components).'),
	('9010', 'Zhonyas Paradox', 'The first instance of damage that would reduce the wearer below @PercentHealthThreshold@% Health is prevented, causing them to become invulnerable for @InvulnDuration@ seconds.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('6', 'Negatron Cloak', '%i:scaleMR% +@MagicResist@ Magic Resist'),
	('2197', 'Bruiser Emblem', 'The holder gains the Bruiser trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('25', 'Titans Resolve', 'When the holder attacks or takes damage, they gain @StackingAD@ Attack Damage and Ability Power. <br><br>This stacks up to @StackCap@ times, at which point the holder gains @BonusResistsAtStackCap@ Armor and Magic Resist.'),
	('2193', 'Socialite Emblem', 'The holder gains the Socialite trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('2190', 'Mutant Emblem', 'The holder gains the Mutant trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('26', 'Runaans Hurricane', 'The holder gains %i:scaleAD% @AD@ Attack Damage. The holders attacks fire a bolt at another nearby enemy, dealing @MultiplierForDamage@% of the holders Attack Damage as physical damage.'),
	('-89', 'tft_item_name_Mittens', 'tft_item_description_IsYordle'),
	('10003', 'B.F. Sword', '%i:scaleAD% +@AD@ Attack Damage'),
	('9', 'Sparring Gloves', '+@CritChance@ Critical Strike Chance<br>+@DodgeChance@ Dodge Chance'),
	('16', 'Bloodthirster', 'Physical damage heals the holder for @Lifesteal@% of the damage dealt. Upon falling below @HealthThreshold@% Health, the holder gains a @ShieldHealthPercent@% maximum Health shield that lasts up to @ShieldDuration@ seconds.'),
	('2214', '10 Gold', '10 Gold'),
	('34', 'Archangels Staff', 'During combat, the holder gains %i:scaleAP% @APPerInterval@ Ability Power every @IntervalSeconds@ seconds.'),
	('2195', 'Scrap Emblem', 'The holder gains the Scrap trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('-58', 'Knights Vow', 'Extra %i:scaleArmor% +@Armor@<br>Holder is also a Knight<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('70', 'Debonair Emblem', 'The holder gains the Debonair trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('38', 'Arcanist Emblem', 'The holder gains the Arcanist trait.<br><br><tftitemrules>[Unique - only 1 per champion</tftitemrules>'),
	('-78', 'TFT_item_name_FrozenMallet', 'TFT_item_description_FrozenMallet'),
	('28', 'Challenger Emblem', 'The holder gains the Challenger trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2222', 'Rune of Allegiance', 'Place on a champion to transfer that champion to your partner, along with all items the champion has equipped.<br><br><tftitemrules>[Cannot be used in combat.] <br>[CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('27', 'ZzRot Portal', 'At the start of combat, the holder taunts enemies within @HexRadius@ hexes. <br><br>When the holder dies, a Voidspawn arises taunting nearby enemies. Voidspawns that arise from summoned units are @SummonedStatReduction@% effective.'),
	('-1', 'tft_item_name_HextechChestguard', 'tft_item_description_HextechChestguard'),
	('9100', 'TFT6_Item_Name_EliteSpotlight', 'TFT6_Item_Description_EliteSpotlight'),
	('9002', 'Deaths Defiance', '@IgnorePainPercent@% of the damage the holder receives is instead dealt over @BleedDuration@ seconds as non-lethal damage. The holders Attacks and Abilities also heal for @BaseHeal@% of damage dealt.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('-48', 'tft_item_name_Darkin', 'tft_item_description_Darkin'),
	('14', 'Spear of Shojin', 'The holders attacks restore %i:scaleMana% @FlatManaRestore@ additional Mana. '),
	('-18', 'Youmuus Ghostblade', 'The holder is also an Assassin.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('8', 'Spatula', 'It must do <i>something</i>...'),
	('68', 'Syndicate Emblem', 'The holder gains the Syndicate trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2199', 'Sniper Emblem', 'The holder gains the Sniper trait.<br><br><tftitemrules>[Unique - only 1 per champion<br>Elusive - cannot be crafted.]</tftitemrules>'),
	('9004', 'Infinity Force', '<tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('35', 'Locket of the Iron Solari', 'When combat begins, the holder and all allies within @HexRange@ hexes in the same row gain a shield that blocks @1StarShieldValue@/@2StarShieldValue@/@3StarShieldValue@ %i:star% damage for @ShieldDuration@ seconds.'),
	('-38', 'TFT_item_name_Yuumi', 'TFT_item_description_Yuumi'),
	('37', 'Morellonomicon', 'When the holder deals magic or true damage with their Ability, they burn the target, dealing @BurnPercent@% of the targets maximum Health as true damage over @BurnDuration@ seconds, and reducing healing by @GrievousWoundsPercent@% for the duration of the burn.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('22', 'Rapid Firecannon', 'Increases the holders Attack Range by @HexRangeIncrease@ hex and grants %i:scaleAS% @TooltipBonusAS@% bonus Attack Speed (including components). The holders attacks can no longer miss.'),
	('204', 'Target Dummy', 'Use on a champion to spawn a movable target dummy nearby. <br><br><tftitemrules> [Cannot be used in combat. <br>CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('1', 'B.F. Sword', '%i:scaleAD% +@AD@ Attack Damage'),
	('201', 'Loaded Dice', 'Use on a champion to reroll a special Shop that contains only champions sharing a Trait with the source champion. <br><br><tftitemrules>[CONSUMABLE - This item disappears when used.]</tftitemrules>'),
	('-35', 'Zhonyas Hourglass', 'On falling below @HealthPercent@% Health, become untargetable, invulnerable, but unable to move for @StasisDuration@ seconds.'),
	('71', 'Striker Emblem', 'The holder gains the Striker trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('29', 'Last Whisper', 'When the holder inflicts a critical hit, the targets Armor is reduced by @ArmorReductionPercent@% for @ArmorBreakDuration@ seconds. This effect does not stack.<br><br><tftitemrules>[Unique - only one per champion]</tftitemrules>'),
	('89', 'Assassin Emblem', 'The holder gains the Assassin trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('39', 'Jeweled Gauntlet', 'The holders magic and true damage from their Ability can critically strike. The holder gains @CritDamageAmp@% bonus Critical Strike Damage and %i:scaleAP% @TooltipBonusAP@ bonus Ability Power.'),
	('7', 'Giants Belt', '%i:scaleHealth% +@Health@ Health'),
	('100', 'Spatula', 'It must do <i>something</i>...'),
	('10002', 'Jammed!', 'Item temporarily disabled'),
	('10001', 'Loot Bag', 'Loot goes here'),
	('2202', 'Three 2-Cost Units', 'Three 2-Cost Units'),
	('3', 'Needlessly Large Rod', '%i:scaleAP% +@AP@ Ability Power'),
	('541', 'Mortal Reminder', 'TFT_item_description_MortalReminder'),
	('9007', 'Randuins Sanctum', 'At the start of combat, all allies adjacent to the wearer gain %i:scaleArmor% @BonusDefense@ Armor and %i:scaleMR% @BonusDefense@ Magic Resistance for the rest of combat.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('10005', 'tft_item_name_SwordOfTheDivine2', 'tft_item_description_SwordOfTheDivine2'),
	('-29', 'tft_item_name_SwordOfTheDivine2', 'tft_item_description_SwordOfTheDivine2'),
	('88', 'Tacticians Crown', 'The holders team gains +@MaxArmySizeIncrease@ maximum team size.'),
	('48', 'Academy Emblem', 'The holder gains the Academy trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('69', 'Quicksilver', 'The holder gains %i:scaleAS% @AS@% bonus Attack Speed. The holder is immune to crowd control in combat for @SpellShieldDuration@ seconds.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('11', 'Deathblade', 'The holder gains %i:scaleAD% @Tooltip1StarBonusAD@/@Tooltip2StarBonusAD@/@Tooltip3StarBonusAD@ %i:star% bonus Attack Damage (including components).'),
	('46', 'Chalice of Power', 'When combat begins, the holder and all allies within @HexRange@ hex in the same row gain %i:scaleAP% @BonusAP@ Ability Power for the rest of combat.'),
	('77', 'Warmogs Armor', 'Grants %i:scaleHealth% @Health@ bonus Health (including components).'),
	('72', 'Hextech Emblem', 'The holder gains the Hextech trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('78', 'Chemtech Emblem', 'The holder gains the Chemtech trait.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('24', 'Statikk Shiv', 'The holder gains %i:scaleAS% @BonusAS@% bonus Attack Speed. Every 3rd attack from the holder unleashes a chain lightning that bounces to @1StarBounces@ enemies, dealing @Damage@ magic damage and reducing their Magic Resist by @MRShred@% for @MRShredDuration@ seconds. '),
	('9009', 'Gold Collector', 'The holder executes enemies below @ExecutePercent@% on hit. Executions have a @GoldChance@% chance to generate 1 gold.<br><br><tftitemrules>[Unique - only 1 per champion]</tftitemrules>'),
	('2221', 'Special Item + 4 Gold', 'Special Item + 4 Gold'),
	('999', 'Unusable Slot', 'This slot cant hold an item.'),
	('13', 'Hextech Gunblade', 'The holders magic and true damage from Abilities heal them for @OmniVamp@% of the damage dealt. The holder also heals their lowest Health ally for the same amount.'),
	('10202', 'tft_item_name_MountainHexBuff', 'tft_item_description_MountainHexBuff'),
	('2205', 'Three 3+Cost Units', 'Three 3+Cost Units');
